/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas_SENAP;

import static Pantallas_SENAP.Conteos.Entidad;
import static Pantallas_SENAP.Conteos.Periodo;
import static Pantallas_SENAP.Valida.Entidad;
import static Pantallas_SENAP.Valida.Periodo;
import ValidacionesSENAP.ExportaxlsxValida;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPActosInvestigacion;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPCarpetaInvestigacion;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPControl;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPDelitos;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPDeterminacion;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPEtapaIntermedia;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPImputadoDelito;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPInvestigacionComplementaria;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPMASC;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPMandamientosJudiciales;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPMedidasCautelares;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPNoticiaCriminal;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPProceso;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPSentencia;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPSobreseimiento;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPSuspensionCondicional;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPVictimaImputado;
import mx.org.inegi.ExportaPlantillaSenap.ExportaPVictimasDelitos;
import mx.org.inegi.QuerysGeneralOracle.SENAP.QueryOracle;

/**
 *
 * @author ANDREA.HERNANDEZL
 */
public class Exporta extends javax.swing.JFrame {

    /**
     * Creates new form Exporta
     */
    public static String Entidad = "", Periodo = "";
    
    public Exporta() {
        initComponents();
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CEntidad = new javax.swing.JComboBox<>();
        CPeriodo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setText("SENAP");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo CNG.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(104, 104, 104)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setText("Entidad:");

        jLabel4.setText("Periodo:");

        CEntidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));
        CEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEntidadActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ExportaCSV.jpg"))); // NOI18N
        jButton1.setText("Exporta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(CPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Thread(() -> {
            Valores_E();
            System.out.println("Entidad" + Entidad);
            System.out.println("Periodo" + Periodo);
            if (!Periodo.equals("")) {
                ExportaPControl EPC = new ExportaPControl();
                ExportaPNoticiaCriminal PC = new ExportaPNoticiaCriminal();
                ExportaPCarpetaInvestigacion PCI = new ExportaPCarpetaInvestigacion();
                ExportaPActosInvestigacion EPAI = new ExportaPActosInvestigacion();
                ExportaPDelitos EPD = new ExportaPDelitos();
                ExportaPVictimasDelitos EPVD = new ExportaPVictimasDelitos();
                ExportaPImputadoDelito EPID = new ExportaPImputadoDelito();
                ExportaPVictimaImputado EPVI = new ExportaPVictimaImputado();
                ExportaPDeterminacion EPDET = new ExportaPDeterminacion();
                ExportaPProceso EPP = new ExportaPProceso();
                ExportaPMandamientosJudiciales EPMJ = new ExportaPMandamientosJudiciales();
                ExportaPInvestigacionComplementaria EPIC = new ExportaPInvestigacionComplementaria();
                ExportaPMedidasCautelares EPMC = new ExportaPMedidasCautelares();
                ExportaPEtapaIntermedia EPEI = new ExportaPEtapaIntermedia();
                ExportaPMASC EPMASC = new ExportaPMASC();
                ExportaPSobreseimiento EPSB = new ExportaPSobreseimiento();
                ExportaPSuspensionCondicional EPSC = new ExportaPSuspensionCondicional();
                ExportaPSentencia EPSEN = new ExportaPSentencia();
                try {
                    jButton1.setEnabled(false);
                    CEntidad.setEnabled(false);
                    CPeriodo.setEnabled(false);
                    QueryOracle Q = new QueryOracle();
                    Q.Actualiza_Estatus_Validacion(Entidad, Periodo);
                    EPC.exportarPControl(Entidad, Periodo);
                    PC.exportarPNoticiCriminal(Entidad, Periodo);
                    PCI.ExportaPCarpetaInvestigacion(Entidad, Periodo);
                    EPAI.exportaPActosInvestigacion(Entidad, Periodo);
                    EPD.exportaPDelitos(Entidad, Periodo);
                    EPVD.exportaPVictimasDelito(Entidad, Periodo);
                    EPID.exportaPImputadoDelito(Entidad, Periodo);
                    EPVI.exportaPVictimaImputado(Entidad, Periodo);
                    EPDET.exportaPDeterminacion(Entidad, Periodo);
                    EPP.exportaPProceso(Entidad, Periodo);
                    EPMJ.exportaPMandamientosJudiciales(Entidad, Periodo);
                    EPIC.exportaPInvestigacionComplementaria(Entidad, Periodo);
                    EPMC.exportaPMedidasCautelares(Entidad, Periodo);
                    EPEI.exportaPEtapaIntermedia(Entidad, Periodo);
                    EPMASC.exportaPMASC(Entidad, Periodo);
                    EPSB.exportaPSobreseimiento(Entidad, Periodo);
                    EPSC.exportaPSuspensionCondicional(Entidad, Periodo);
                    EPSEN.exportaPSentencia(Entidad, Periodo);
                    jButton1.setEnabled(true);
                    CEntidad.setEnabled(true);
                    CPeriodo.setEnabled(true);
                } catch (SQLException ex) {
                    Logger.getLogger(IntegraTMP.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Favor de Seleccionar un periodo");
            }
        }).start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEntidadActionPerformed
        // TODO add your handling code here:
        LLena_combo_Periodo();
    }//GEN-LAST:event_CEntidadActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        LLena_combo_Periodo();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Inicio In = new Inicio();
        In.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    public void Valores_E() {
        Entidad = CEntidad.getSelectedItem().toString();
        if (CPeriodo.getSelectedItem() == null) {
        } else {
            Periodo = CPeriodo.getSelectedItem().toString();
        }

    }
    
    public void LLena_combo_Periodo() {
        QueryOracle Q = new QueryOracle();
        ArrayList<String[]> Array;
        try {
            CPeriodo.removeAllItems();
            Array = Q.Periodo(CEntidad.getSelectedItem().toString());
            for (String[] elemento : Array) {
                CPeriodo.addItem(elemento[0]);
            }

        } catch (SQLException ex) {
            Logger.getLogger(IntegraTR.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exporta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exporta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exporta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exporta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exporta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CEntidad;
    private javax.swing.JComboBox<String> CPeriodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
