/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_PLE;

import java.awt.FileDialog;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.org.inegi.Procedure.PLE.EliminaTMP;
import mx.org.inegi.QuerysGeneral.PLE.Querys;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_1;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_1A;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_1B;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_1C;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_1D;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_1_CSV;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_2;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_3;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_4;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_5;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_6;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_7;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_8;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_9;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Integrar_TMP extends javax.swing.JFrame {
    
    public static String RutaAr="",Entidad="",Envio="",Legislatura="",Procedure="";
    public static boolean ventanaAbierta = false;
    String Estatus="";
            
       

    /**
     * Creates new form Integrar_TMP
     */
    public Integrar_TMP() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        RutaArchivo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        CEntidad = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        ENVIO = new javax.swing.JLabel();
        ENVIO1 = new javax.swing.JLabel();
        TLegislatura = new javax.swing.JTextField();
        TEnvio = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        Cproceso = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        Ttabla = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CEstatus = new javax.swing.JComboBox();
        ButtonCsv = new javax.swing.JRadioButton();
        ButtonXlsx = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo CNG.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setText("Poderes Legislativos Estatales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("....");
        jButton1.setToolTipText("Seleccionar Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Ruta archivo:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/errorins.png"))); // NOI18N
        jButton2.setToolTipText("Errores de Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InsertaBD.png"))); // NOI18N
        jButton3.setText("Insertar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        CEntidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));

        jLabel4.setText("Entidad:");

        ENVIO.setText("Envio:");

        ENVIO1.setText("Legislatura:");

        jLabel5.setText("Progreso...");

        Cproceso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL_TABLES", "TMP_PLE_MEDS1_1", "TMP_PLE_MEDS1_1A", "TMP_PLE_MEDS1_1B", "TMP_PLE_MEDS1_1C", "TMP_PLE_MEDS1_1D", "TMP_PLE_MEDS1_2", "TMP_PLE_MEDS1_3", "TMP_PLE_MEDS1_4", "TMP_PLE_MEDS1_5", "TMP_PLE_MEDS1_6", "TMP_PLE_MEDS1_7", "TMP_PLE_MEDS1_8", "TMP_PLE_MEDS1_9" }));

        jLabel6.setText("Procedure:");

        jLabel7.setText("Estatus:");

        CEstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "En Revision", "Liberado" }));
        CEstatus.setEnabled(false);

        buttonGroup1.add(ButtonCsv);
        ButtonCsv.setLabel("CSV");
        ButtonCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCsvActionPerformed(evt);
            }
        });

        buttonGroup1.add(ButtonXlsx);
        ButtonXlsx.setText("XLSX");
        ButtonXlsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonXlsxActionPerformed(evt);
            }
        });

        jLabel8.setText("Formato de Archivo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 31, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 438, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(62, 62, 62))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 94, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ButtonCsv)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ButtonXlsx))
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(RutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))
                                .addGap(45, 45, 45))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ttabla, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(15, 15, 15))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(CEntidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TLegislatura))
                            .addComponent(ENVIO1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ENVIO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Cproceso, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ENVIO, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ENVIO1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TLegislatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCsv)
                    .addComponent(ButtonXlsx)
                    .addComponent(jLabel8))
                .addGap(36, 36, 36)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cproceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Ttabla, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      RutaArchivo.setText("");
        String directorio="";
        String nombreArchivo="";
        FileDialog dialogoArchivo;
        dialogoArchivo = new FileDialog(this, "ARCHIVOS RALAB",FileDialog.LOAD);
        dialogoArchivo.setVisible(true);
        if(dialogoArchivo.getFile()!=null){ /* Validar que se haya Seleccionado un Archivo*/
             directorio = dialogoArchivo.getDirectory();
             nombreArchivo =dialogoArchivo.getFile();
             RutaArchivo.setText(directorio+nombreArchivo);
              RutaAr=directorio+nombreArchivo;  
        }     
          
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

  public void EnableFalse(){
      TEnvio.setEnabled(false);
         TLegislatura.setEnabled(false);
         CEntidad.setEnabled(false);
         jButton1.setEnabled(false);
         jButton3.setEnabled(false);
         jButton2.setEnabled(false);
         Cproceso.setEnabled(false);
  }
  
   public void EnableTrue(){
      TEnvio.setEnabled(true);
         TLegislatura.setEnabled(true);
         CEntidad.setEnabled(true);
         jButton1.setEnabled(true);
         jButton3.setEnabled(true);
         jButton2.setEnabled(true);
         Cproceso.setEnabled(true);
  }
  
  
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (ButtonCsv.isSelected()){
            System.out.println("boton csv");
            Tmp_ple_meds1_1_CSV meds1_1 =new Tmp_ple_meds1_1_CSV();
            try {
                Valores();
                meds1_1.Meds1_1_CSV(RutaAr, Entidad, Envio, Legislatura, Estatus);
            } catch (Exception ex) {
                Logger.getLogger(Integrar_TMP.class.getName()).log(Level.SEVERE, null, ex);
            }
         /*   if (Procedure.equals("ALL_TABLES"))
             {
                try {
                    EliminaTMP Elimina=new EliminaTMP();
                    Elimina.EliminaTMP(Entidad, Envio, Legislatura);
                } catch (SQLException ex) {
                    Logger.getLogger(Integrar_TMP.class.getName()).log(Level.SEVERE, null, ex);
                }
             }*/
            
        }
        else{
            
            System.out.println("boton xlsx");
        

   new Thread(() -> {    
    Querys Q =new Querys();   
    if (!RutaArchivo.getText().equals("")){     
     if (!TEnvio.getText().equals("") && !TLegislatura.getText().equals("") ){    
         Valores();
          Estatus=Q.Estatus(Entidad, Legislatura, Envio);
          
       if (!Estatus.equals("Liberado"))   
       {
         EnableFalse();
         Tmp_ple_meds1_1 ple_meds1_1 =new Tmp_ple_meds1_1();
         Tmp_ple_meds1_1A ple_meds1_1A =new Tmp_ple_meds1_1A();
         Tmp_ple_meds1_1B ple_meds1_1B =new Tmp_ple_meds1_1B();
         Tmp_ple_meds1_1C ple_meds1_1C =new Tmp_ple_meds1_1C();
         Tmp_ple_meds1_1D ple_meds1_1D =new Tmp_ple_meds1_1D();
         Tmp_ple_meds1_2 ple_meds1_2 =new Tmp_ple_meds1_2();
         Tmp_ple_meds1_3 ple_meds1_3 =new Tmp_ple_meds1_3();
         Tmp_ple_meds1_4 ple_meds1_4 =new Tmp_ple_meds1_4();
         Tmp_ple_meds1_5 ple_meds1_5 =new Tmp_ple_meds1_5();
         Tmp_ple_meds1_6 ple_meds1_6 =new Tmp_ple_meds1_6();
         Tmp_ple_meds1_7 ple_meds1_7 =new Tmp_ple_meds1_7();
         Tmp_ple_meds1_8 ple_meds1_8 =new Tmp_ple_meds1_8();
         Tmp_ple_meds1_9 ple_meds1_9 =new Tmp_ple_meds1_9();
         
         try { 
             jProgressBar1.setVisible(true);
             Ttabla.setVisible(true);
             jLabel5.setVisible(true);
             jProgressBar1.setValue(0);
             if (Procedure.equals("ALL_TABLES"))
             {
             EliminaTMP Elimina=new EliminaTMP(); 
             Elimina.EliminaTMP(Entidad, Envio, Legislatura);
             Ttabla.setText("");    
             jProgressBar1.setValue(3);
             Ttabla.setText("TMP_PLE_MEDS1_1");
             ple_meds1_1.In_Tmp_ple_meds1_1(Entidad,Envio,Legislatura,CEstatus.getSelectedItem().toString());
              jProgressBar1.setValue(7);
              Ttabla.setText("TMP_PLE_MEDS1_1A");
             ple_meds1_1A.in_Tmp_ple_meds1_1A(Entidad, Envio, Legislatura);
              jProgressBar1.setValue(14);
               Ttabla.setText("TMP_PLE_MEDS1_1B");
              ple_meds1_1B.Tmp_ple_meds1_1B(Entidad, Envio, Legislatura);
              jProgressBar1.setValue(21);
               Ttabla.setText("TMP_PLE_MEDS1_1C");
              ple_meds1_1C.Tmp_ple_meds1_1C(Entidad, Envio, Legislatura);
              jProgressBar1.setValue(27);
               Ttabla.setText("TMP_PLE_MEDS1_1D");
              ple_meds1_1D.Tmp_ple_meds1_1D(Entidad, Envio, Legislatura);
              jProgressBar1.setValue(34);
               Ttabla.setText("TMP_PLE_MEDS1_2");
              ple_meds1_2.Tmp_ple_meds1_2(Entidad, Envio, Legislatura);
              jProgressBar1.setValue(41);
              Ttabla.setText("TMP_PLE_MEDS1_3");
              ple_meds1_3.Tmp_ple_meds1_3(Entidad, Envio, Legislatura);
              jProgressBar1.setValue(48);
              Ttabla.setText("TMP_PLE_MEDS1_4");
              ple_meds1_4.Tmp_ple_meds1_4(Entidad, Envio, Legislatura);
              jProgressBar1.setValue(56);
              Ttabla.setText("TMP_PLE_MEDS1_5");
              ple_meds1_5.Tmp_ple_meds1_5(Entidad, Envio, Legislatura);
              jProgressBar1.setValue(64);
              Ttabla.setText("TMP_PLE_MEDS1_6");
              ple_meds1_6.Tmp_ple_meds1_6(Entidad, Envio, Legislatura);
              jProgressBar1.setValue(72);
              Ttabla.setText("TMP_PLE_MEDS1_7");
              ple_meds1_7.Tmp_ple_meds1_7(Entidad, Envio, Legislatura);
              jProgressBar1.setValue(80);
              Ttabla.setText("TMP_PLE_MEDS1_8");
              ple_meds1_8.Tmp_ple_meds1_8(Entidad, Envio, Legislatura);
               jProgressBar1.setValue(90);
               Ttabla.setText("TMP_PLE_MEDS1_9");
              ple_meds1_9.Tmp_ple_meds1_9(Entidad, Envio, Legislatura);
              jProgressBar1.setValue(100);
              JOptionPane.showMessageDialog(null, "Informacion insertada a TMP,favor de revisar pantalla errores de insert");
              
             }
             if (Procedure.equals("TMP_PLE_MEDS1_1")){
                 jProgressBar1.setValue(15);
                 ple_meds1_1.In_Tmp_ple_meds1_1(Entidad,Envio,Legislatura,CEstatus.getSelectedItem().toString());
                 jProgressBar1.setValue(100);
                 JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
             }
             if (Procedure.equals("TMP_PLE_MEDS1_1A")){
                 jProgressBar1.setValue(15);
                 ple_meds1_1A.in_Tmp_ple_meds1_1A(Entidad, Envio, Legislatura);
                 jProgressBar1.setValue(100);
                JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
             }
                   if (Procedure.equals("TMP_PLE_MEDS1_1B")){
                jProgressBar1.setValue(15);
                ple_meds1_1B.Tmp_ple_meds1_1B(Entidad, Envio, Legislatura);
                jProgressBar1.setValue(100);
                JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
             }
                if (Procedure.equals("TMP_PLE_MEDS1_1C")){
                jProgressBar1.setValue(15);    
                ple_meds1_1C.Tmp_ple_meds1_1C(Entidad, Envio, Legislatura);
                jProgressBar1.setValue(100);
                JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
             }
             if (Procedure.equals("TMP_PLE_MEDS1_1D")){
                jProgressBar1.setValue(15); 
                ple_meds1_1D.Tmp_ple_meds1_1D(Entidad, Envio, Legislatura);
                jProgressBar1.setValue(100);
                JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
             }    
             if (Procedure.equals("TMP_PLE_MEDS1_2")){
                jProgressBar1.setValue(15); 
                ple_meds1_2.Tmp_ple_meds1_2(Entidad, Envio, Legislatura);
                jProgressBar1.setValue(100);
                JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
             }   
             if (Procedure.equals("TMP_PLE_MEDS1_3")){
                jProgressBar1.setValue(15); 
                ple_meds1_3.Tmp_ple_meds1_3(Entidad, Envio, Legislatura);
                jProgressBar1.setValue(100);
                JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
             }   
             if (Procedure.equals("TMP_PLE_MEDS1_4")){
                jProgressBar1.setValue(15); 
                ple_meds1_4.Tmp_ple_meds1_4(Entidad, Envio, Legislatura);
                jProgressBar1.setValue(100);
                JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
             }  
             if (Procedure.equals("TMP_PLE_MEDS1_5")){
                jProgressBar1.setValue(15); 
                ple_meds1_5.Tmp_ple_meds1_5(Entidad, Envio, Legislatura);
                jProgressBar1.setValue(100);
                JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
             }  
             if (Procedure.equals("TMP_PLE_MEDS1_6")){
                jProgressBar1.setValue(15); 
                ple_meds1_6.Tmp_ple_meds1_6(Entidad, Envio, Legislatura);
                jProgressBar1.setValue(100);
                JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
             }  
             if (Procedure.equals("TMP_PLE_MEDS1_7")){
                jProgressBar1.setValue(15); 
                ple_meds1_7.Tmp_ple_meds1_7(Entidad, Envio, Legislatura);
                jProgressBar1.setValue(100);
                JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
             }  
             if (Procedure.equals("TMP_PLE_MEDS1_8")){
                jProgressBar1.setValue(15); 
                ple_meds1_8.Tmp_ple_meds1_8(Entidad, Envio, Legislatura);
                jProgressBar1.setValue(100);
                JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
             }  
             if (Procedure.equals("TMP_PLE_MEDS1_9")){
                jProgressBar1.setValue(15); 
                ple_meds1_9.Tmp_ple_meds1_9(Entidad, Envio, Legislatura);
                jProgressBar1.setValue(100);
                JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
             }  
             jLabel5.setVisible(false);
             jProgressBar1.setVisible(false);
              Ttabla.setVisible(false);
             EnableTrue();
         } catch (Exception ex) {
             Logger.getLogger(Integrar_TMP.class.getName()).log(Level.SEVERE, null, ex);
         }
    
       }else{
          JOptionPane.showMessageDialog(null, "La informacion se encuentra en estatus liberado-Entidad:"+Entidad+" Leg:"+Legislatura+" Envio:"+Envio); 
       }
       
       }else
         JOptionPane.showMessageDialog(null, "Favor de capturar Envio y Legislatura");
    
   }else
       JOptionPane.showMessageDialog(null, "Favor de seleccionar archivo");
     }).start();
        
        }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Valores();
        if (!TEnvio.getText().equals("") && !TLegislatura.getText().equals("") && !CEntidad.getSelectedItem().toString().equals("")) {
            if (!ventanaAbierta) {
                ventanaAbierta = true;
                Errores_InsertTMP Errores = new Errores_InsertTMP();
                Errores.setVisible(true);
               
            } else {
                 JOptionPane.showMessageDialog(null, "Ventana Errores de insert abierta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Favor de capturar Entidad,Envio y Legislatura");
        }

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
             jLabel5.setVisible(false);
             jProgressBar1.setVisible(false);
             RutaArchivo.setEnabled(false);
             Ttabla.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void ButtonCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCsvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCsvActionPerformed

    private void ButtonXlsxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonXlsxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonXlsxActionPerformed
  
    
    public void Valores(){
        Entidad=CEntidad.getSelectedItem().toString();
        Envio=TEnvio.getText();
        Legislatura=TLegislatura.getText();
        Procedure=Cproceso.getSelectedItem().toString();
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Integrar_TMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Integrar_TMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Integrar_TMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Integrar_TMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Integrar_TMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ButtonCsv;
    private javax.swing.JRadioButton ButtonXlsx;
    private javax.swing.JComboBox CEntidad;
    private javax.swing.JComboBox CEstatus;
    private javax.swing.JComboBox Cproceso;
    private javax.swing.JLabel ENVIO;
    private javax.swing.JLabel ENVIO1;
    private javax.swing.JTextField RutaArchivo;
    private javax.swing.JTextField TEnvio;
    private javax.swing.JTextField TLegislatura;
    private javax.swing.JLabel Ttabla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
