/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_PLE;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.org.inegi.QuerysGeneral.PLE.Querys;
import mx.org.inegi.insert_TR.PLE.ALL_TABLES;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_1;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_1A;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_1B;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_1C;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_1D;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_2;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_3;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_3A;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_4;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_5;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_6;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_7;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_8;
import mx.org.inegi.insert_TR.PLE.TR_ple_meds1_9;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Integrar_TR extends javax.swing.JFrame {

    /**
     * Creates new form Integrar_TR
     */
    
    public static String RutaAr,Entidad="",Envio="",Legislatura="",Procedure="";
    public static boolean ventanaAbierta = false;
    
    public Integrar_TR() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_PPLE = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Btn_errores_insert = new javax.swing.JButton();
        Btn_Insertar_TR = new javax.swing.JButton();
        CEntidad = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        ENVIO = new javax.swing.JLabel();
        ENVIO1 = new javax.swing.JLabel();
        TLegislatura = new javax.swing.JTextField();
        TEnvio = new javax.swing.JTextField();
        Cproceso = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        Ttabla = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CEstatus = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Panel_PPLE.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo CNG.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setText("Poderes Legislativos Estatales");

        javax.swing.GroupLayout Panel_PPLELayout = new javax.swing.GroupLayout(Panel_PPLE);
        Panel_PPLE.setLayout(Panel_PPLELayout);
        Panel_PPLELayout.setHorizontalGroup(
            Panel_PPLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PPLELayout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        Panel_PPLELayout.setVerticalGroup(
            Panel_PPLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PPLELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_PPLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_PPLELayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Btn_errores_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/errorins.png"))); // NOI18N
        Btn_errores_insert.setToolTipText("Errores de Insert");
        Btn_errores_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_errores_insertActionPerformed(evt);
            }
        });

        Btn_Insertar_TR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InsertaBD.png"))); // NOI18N
        Btn_Insertar_TR.setText("Insertar");
        Btn_Insertar_TR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Insertar_TRMouseClicked(evt);
            }
        });
        Btn_Insertar_TR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Insertar_TRActionPerformed(evt);
            }
        });

        CEntidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));

        jLabel4.setText("Entidad:");

        ENVIO.setText("Envio:");

        ENVIO1.setText("Legislatura:");

        Cproceso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL_TABLES", "TR_PLE_MEDS1_1", "TR_PLE_MEDS1_1A", "TR_PLE_MEDS1_1B", "TR_PLE_MEDS1_1C", "TR_PLE_MEDS1_1D", "TR_PLE_MEDS1_2", "TR_PLE_MEDS1_3", "TR_PLE_MEDS1_3A", "TR_PLE_MEDS1_4", "TR_PLE_MEDS1_5", "TR_PLE_MEDS1_6", "TR_PLE_MEDS1_7", "TR_PLE_MEDS1_8", "TR_PLE_MEDS1_9" }));

        jLabel6.setText("Procedure:");

        jLabel7.setText("Estatus:");

        CEstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "En Revision", "Liberado" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refresh.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Insertar_TR)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(11, Short.MAX_VALUE)
                        .addComponent(Ttabla, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 276, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TLegislatura))
                            .addComponent(ENVIO1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ENVIO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_errores_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Cproceso, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Btn_errores_insert))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ENVIO, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ENVIO1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TLegislatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cproceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(Btn_Insertar_TR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Ttabla, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_PPLE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_PPLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_errores_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_errores_insertActionPerformed
        // TODO add your handling code here:
        Valores();
        if (!TEnvio.getText().equals("") && !TLegislatura.getText().equals("") && !CEntidad.getSelectedItem().toString().equals("")) {
            if (!ventanaAbierta) {
                ventanaAbierta = true;
                Errores_InsertTR Errores = new Errores_InsertTR();
                Errores.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Ventana Errores de insert abierta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Favor de capturar Entidad,Envio y Legislatura");
        }

    }//GEN-LAST:event_Btn_errores_insertActionPerformed

    public void Valores(){
        Entidad=CEntidad.getSelectedItem().toString();
        Envio=TEnvio.getText();
        Legislatura=TLegislatura.getText();
        Procedure=Cproceso.getSelectedItem().toString(); 
    }
    
    
    private void Btn_Insertar_TRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Insertar_TRActionPerformed
        // TODO add your handling code here:
        ALL_TABLES ALL=new ALL_TABLES();
        TR_ple_meds1_1 TR1= new TR_ple_meds1_1();
        TR_ple_meds1_1A TR1A= new TR_ple_meds1_1A();
        TR_ple_meds1_1B TR1B= new TR_ple_meds1_1B();
        TR_ple_meds1_1C TR1C= new TR_ple_meds1_1C();
        TR_ple_meds1_1D TR1D= new TR_ple_meds1_1D();
        TR_ple_meds1_2 TR2= new TR_ple_meds1_2();
        TR_ple_meds1_3 TR3= new TR_ple_meds1_3();
        TR_ple_meds1_3A TR3A= new TR_ple_meds1_3A();
        TR_ple_meds1_4 TR4= new TR_ple_meds1_4();
        TR_ple_meds1_5 TR5= new TR_ple_meds1_5();
        TR_ple_meds1_6 TR6= new TR_ple_meds1_6();
        TR_ple_meds1_7 TR7= new TR_ple_meds1_7();
        TR_ple_meds1_8 TR8= new TR_ple_meds1_8();
        TR_ple_meds1_9 TR9= new TR_ple_meds1_9();
        BarraInsert Barra=new BarraInsert();
        
        new Thread(() -> {
         
                if (!TEnvio.getText().equals("") && !TLegislatura.getText().equals("") ){
                    Valores();
                    Barra.setVisible(true);
                    try {
                        EnableFalse();
                        if (Procedure.equals("ALL_TABLES"))
                        {
                           ALL.ALL_TABLES(Entidad, Legislatura, Envio);
                           JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                        if (Procedure.equals("TR_PLE_MEDS1_1")){
                           TR1.TR_ple_meds1_1(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                        if (Procedure.equals("TR_PLE_MEDS1_1A")){
                            TR1A.TR_ple_meds1_A(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                        if (Procedure.equals("TR_PLE_MEDS1_1B")){
                            TR1B.TR_ple_meds1_B(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                        if (Procedure.equals("TR_PLE_MEDS1_1C")){
                            TR1C.TR_ple_meds1_C(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                        if (Procedure.equals("TR_PLE_MEDS1_1D")){
                            TR1D.TR_ple_meds1_D(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                        if (Procedure.equals("TR_PLE_MEDS1_2")){
                            TR2.TR_ple_meds1_2(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                        if (Procedure.equals("TR_PLE_MEDS1_3")){
                            TR3.TR_ple_meds1_3(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                         if (Procedure.equals("TR_PLE_MEDS1_3A")){
                            TR3A.TR_ple_meds1_3A(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                        if (Procedure.equals("TR_PLE_MEDS1_4")){
                            TR4.TR_ple_meds1_4(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                        if (Procedure.equals("TR_PLE_MEDS1_5")){
                            TR5.TR_ple_meds1_5(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                        if (Procedure.equals("TR_PLE_MEDS1_6")){
                            TR6.TR_ple_meds1_6(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                        if (Procedure.equals("TR_PLE_MEDS1_7")){
                            TR7.TR_ple_meds1_7(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                        if (Procedure.equals("TR_PLE_MEDS1_8")){
                            TR8.TR_ple_meds1_8(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }
                        if (Procedure.equals("TR_PLE_MEDS1_9")){
                            TR9.TR_ple_meds1_9(Entidad, Legislatura, Envio);
                            JOptionPane.showMessageDialog(null, "Informacion insertada,favor de revisar pantalla errores de insert");
                        }            
                        Barra.setVisible(false);
                        EnableTrue();
                    } catch (Exception ex) {
                        Logger.getLogger(Integrar_TMP.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else
                JOptionPane.showMessageDialog(null, "Favor de capturar Envio y Legislatura");
        }).start();

    }//GEN-LAST:event_Btn_Insertar_TRActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       // Querys Q=new Querys();
       // CEstatus.setSelectedItem(Q.Estatus(Entidad, Legislatura, Envio));
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Querys Q=new Querys();
        Valores();
        Q.Cambio_Estatus(Entidad, Legislatura, Envio, CEstatus.getSelectedItem().toString());
        JOptionPane.showMessageDialog(null, "Cambio de estatus correctamente");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Btn_Insertar_TRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Insertar_TRMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Insertar_TRMouseClicked

    public void EnableFalse(){
      TEnvio.setEnabled(false);
         TLegislatura.setEnabled(false);
         CEntidad.setEnabled(false);
         Btn_Insertar_TR.setEnabled(false);
         Btn_errores_insert.setEnabled(false);
         Cproceso.setEnabled(false);
  }
  
   public void EnableTrue(){
      TEnvio.setEnabled(true);
         TLegislatura.setEnabled(true);
         CEntidad.setEnabled(true);
         Btn_Insertar_TR.setEnabled(true);
         Btn_errores_insert.setEnabled(true);
         Cproceso.setEnabled(true);
  }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Integrar_TR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Integrar_TR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Integrar_TR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Integrar_TR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Integrar_TR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Insertar_TR;
    private javax.swing.JButton Btn_errores_insert;
    private javax.swing.JComboBox CEntidad;
    private javax.swing.JComboBox CEstatus;
    private javax.swing.JComboBox Cproceso;
    private javax.swing.JLabel ENVIO;
    private javax.swing.JLabel ENVIO1;
    private javax.swing.JPanel Panel_PPLE;
    private javax.swing.JTextField TEnvio;
    private javax.swing.JTextField TLegislatura;
    private javax.swing.JLabel Ttabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
