/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_PLE;

import java.awt.FileDialog;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.org.inegi.Procedure.PLE.EliminaTMP;
import mx.org.inegi.QuerysGeneral.PLE.Querys;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_1;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_1A;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_1B;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_1C;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_1D;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_1_CSV;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_2_CSV;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_3_CSV;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_4_CSV;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_5_CSV;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_6_CSV;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_7_CSV;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_8_CSV;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_9_CSV;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_2;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_3;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_4;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_5;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_6;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_7;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_8;
import mx.org.inegi.insert_TMP.PLE.Tmp_ple_meds1_9;
import mx.org.inegi.insert_TMP.PLE.valida_info_correcta_Generales.*;
import mx.org.inegi.insert_TMP.PLE.Periodo;
import mx.org.inegi.insert_TMP.PLE.valida_info_correcta_Generales;


/**
 *
 * @author ANTONIO.CORIA
 */
public class Integrar_TMP extends javax.swing.JFrame {

    public static String RutaAr = "", Entidad = "", Envio = "", Legislatura = "", Procedure = "";
    public static boolean ventanaAbierta = false;
    public static String Estatus = "", directorio = "";

    /**
     * Creates new form Integrar_TMP
     */
    public Integrar_TMP() {
    initComponents();
    this.setLocationRelativeTo(null);

    CAño.removeAllItems(); // opcional, limpia el combo

    CAño.addItem(new ItemCombo("Primer año", 1));
    CAño.addItem(new ItemCombo("Segundo año", 2));
    CAño.addItem(new ItemCombo("Tercer año", 3));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Panel_PLE_ENCABEZADO = new javax.swing.JPanel();
        Label_Logo = new javax.swing.JLabel();
        Panel_Verde = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Panel_PLE_insertarTMP = new javax.swing.JPanel();
        RutaArchivo = new javax.swing.JTextField();
        boton_ruta = new javax.swing.JButton();
        Label_RutaArchivo = new javax.swing.JLabel();
        botón_log_tabla = new javax.swing.JButton();
        Boton_insertar = new javax.swing.JButton();
        CEntidad = new javax.swing.JComboBox();
        Label_entidad = new javax.swing.JLabel();
        Label_envio = new javax.swing.JLabel();
        Label_Legislatura = new javax.swing.JLabel();
        TLegislatura = new javax.swing.JTextField();
        ProgressBar_PLE_TMP = new javax.swing.JProgressBar();
        Label_Progressline = new javax.swing.JLabel();
        Combobox_proceso = new javax.swing.JComboBox();
        Label_Procedure = new javax.swing.JLabel();
        Progressline = new javax.swing.JLabel();
        Label_Estatus = new javax.swing.JLabel();
        CEstatus = new javax.swing.JComboBox();
        RadioButtonCsv = new javax.swing.JRadioButton();
        RadioButtonXlsx = new javax.swing.JRadioButton();
        Label_formatoarchivo = new javax.swing.JLabel();
        Label_Periodo = new javax.swing.JLabel();
        TEnvio = new javax.swing.JTextField();
        CheckBox_1PO = new javax.swing.JCheckBox();
        Label_Year = new javax.swing.JLabel();
        CAño = new javax.swing.JComboBox();
        CheckBox_1PR = new javax.swing.JCheckBox();
        CheckBox_2PO = new javax.swing.JCheckBox();
        CheckBox_3PR = new javax.swing.JCheckBox();
        CheckBox_2PR = new javax.swing.JCheckBox();
        CheckBox_3PO = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Panel_PLE_ENCABEZADO.setBackground(new java.awt.Color(255, 255, 255));

        Label_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo CNG.png"))); // NOI18N

        Panel_Verde.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout Panel_VerdeLayout = new javax.swing.GroupLayout(Panel_Verde);
        Panel_Verde.setLayout(Panel_VerdeLayout);
        Panel_VerdeLayout.setHorizontalGroup(
            Panel_VerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel_VerdeLayout.setVerticalGroup(
            Panel_VerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setText("Poderes Legislativos Estatales");

        javax.swing.GroupLayout Panel_PLE_ENCABEZADOLayout = new javax.swing.GroupLayout(Panel_PLE_ENCABEZADO);
        Panel_PLE_ENCABEZADO.setLayout(Panel_PLE_ENCABEZADOLayout);
        Panel_PLE_ENCABEZADOLayout.setHorizontalGroup(
            Panel_PLE_ENCABEZADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Verde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PLE_ENCABEZADOLayout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        Panel_PLE_ENCABEZADOLayout.setVerticalGroup(
            Panel_PLE_ENCABEZADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PLE_ENCABEZADOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_PLE_ENCABEZADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_PLE_ENCABEZADOLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(17, 17, 17)
                .addComponent(Panel_Verde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel_PLE_insertarTMP.setBackground(new java.awt.Color(255, 255, 255));

        RutaArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutaArchivoActionPerformed(evt);
            }
        });

        boton_ruta.setText("....");
        boton_ruta.setToolTipText("Seleccionar Archivo");
        boton_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_rutaActionPerformed(evt);
            }
        });

        Label_RutaArchivo.setText("Ruta archivo:");

        botón_log_tabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/errorins.png"))); // NOI18N
        botón_log_tabla.setToolTipText("Errores de Insert");
        botón_log_tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botón_log_tablaActionPerformed(evt);
            }
        });

        Boton_insertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InsertaBD.png"))); // NOI18N
        Boton_insertar.setText("Insertar");
        Boton_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Insertar(evt);
            }
        });

        CEntidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));
        CEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEntidadActionPerformed(evt);
            }
        });

        Label_entidad.setText("Entidad:");

        Label_envio.setText("Envio:");

        Label_Legislatura.setText("Legislatura:");

        Label_Progressline.setText("Progreso...");

        Combobox_proceso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL_TABLES", "TMP_PLE_MEDS1_1", "TMP_PLE_MEDS1_1A", "TMP_PLE_MEDS1_1B", "TMP_PLE_MEDS1_1C", "TMP_PLE_MEDS1_1D", "TMP_PLE_MEDS1_2", "TMP_PLE_MEDS1_3", "TMP_PLE_MEDS1_4", "TMP_PLE_MEDS1_5", "TMP_PLE_MEDS1_6", "TMP_PLE_MEDS1_7", "TMP_PLE_MEDS1_8", "TMP_PLE_MEDS1_9" }));
        Combobox_proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combobox_procesoActionPerformed(evt);
            }
        });

        Label_Procedure.setText("Procedure:");

        Label_Estatus.setText("Estatus:");

        CEstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "En Revision", "Liberado" }));
        CEstatus.setEnabled(false);

        buttonGroup1.add(RadioButtonCsv);
        RadioButtonCsv.setLabel("CSV");
        RadioButtonCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonCsvActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButtonXlsx);
        RadioButtonXlsx.setText("XLSX");
        RadioButtonXlsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonXlsxActionPerformed(evt);
            }
        });

        Label_formatoarchivo.setText("Formato de Archivo:");

        Label_Periodo.setText("Periodo(s):");

        CheckBox_1PO.setText("1PO");
        CheckBox_1PO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_1POActionPerformed(evt);
            }
        });

        Label_Year.setText("Año:");

        CAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAñoActionPerformed(evt);
            }
        });

        CheckBox_1PR.setText("1PR");
        CheckBox_1PR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_1PRActionPerformed(evt);
            }
        });

        CheckBox_2PO.setText("2PO");
        CheckBox_2PO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_2POActionPerformed(evt);
            }
        });

        CheckBox_3PR.setText("3PR");
        CheckBox_3PR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_3PRActionPerformed(evt);
            }
        });

        CheckBox_2PR.setText("2PR");
        CheckBox_2PR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_2PRActionPerformed(evt);
            }
        });

        CheckBox_3PO.setText("3PO");
        CheckBox_3PO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_3POActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_PLE_insertarTMPLayout = new javax.swing.GroupLayout(Panel_PLE_insertarTMP);
        Panel_PLE_insertarTMP.setLayout(Panel_PLE_insertarTMPLayout);
        Panel_PLE_insertarTMPLayout.setHorizontalGroup(
            Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PLE_insertarTMPLayout.createSequentialGroup()
                .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ProgressBar_PLE_TMP, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 210, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_PLE_insertarTMPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                                .addComponent(Label_entidad)
                                .addGap(15, 15, 15))
                            .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                                .addComponent(CEntidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TLegislatura))
                            .addComponent(Label_Legislatura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_envio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Year))
                        .addGap(28, 28, 28)
                        .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                                .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_Periodo)
                                    .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                                        .addComponent(CheckBox_1PO)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CheckBox_1PR)))
                                .addGap(45, 45, 45)
                                .addComponent(botón_log_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                                .addComponent(CheckBox_2PO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckBox_2PR))
                            .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                                .addComponent(CheckBox_3PO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckBox_3PR))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_PLE_insertarTMPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Label_Progressline, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                                .addComponent(Progressline, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Boton_insertar))
                            .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                                .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_Procedure)
                                    .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                                        .addComponent(Label_Estatus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(Label_formatoarchivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RadioButtonCsv)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RadioButtonXlsx))
                                    .addComponent(Label_RutaArchivo))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PLE_insertarTMPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_ruta)
                    .addComponent(Combobox_proceso, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );
        Panel_PLE_insertarTMPLayout.setVerticalGroup(
            Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                        .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botón_log_tabla)
                            .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                                .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Label_Legislatura, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Label_entidad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Label_Year)
                                        .addComponent(Label_Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TLegislatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckBox_1PO)
                                    .addComponent(CheckBox_1PR))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckBox_2PO)
                            .addComponent(CheckBox_2PR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckBox_3PO)
                            .addComponent(CheckBox_3PR))
                        .addGap(29, 29, 29)
                        .addComponent(Label_RutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                        .addComponent(Label_envio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)))
                .addComponent(RutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_ruta)
                .addGap(29, 29, 29)
                .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Estatus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_formatoarchivo)
                    .addComponent(RadioButtonCsv)
                    .addComponent(RadioButtonXlsx))
                .addGap(27, 27, 27)
                .addComponent(Label_Procedure, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Combobox_proceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PLE_insertarTMPLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(Panel_PLE_insertarTMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Progressline)
                            .addComponent(Progressline, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PLE_insertarTMPLayout.createSequentialGroup()
                        .addComponent(Boton_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addComponent(ProgressBar_PLE_TMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_PLE_ENCABEZADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_PLE_insertarTMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_PLE_ENCABEZADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_PLE_insertarTMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_rutaActionPerformed
        // TODO add your handling code here:
        RutaArchivo.setText("");

        String nombreArchivo = "";
        FileDialog dialogoArchivo;
        dialogoArchivo = new FileDialog(this, "ARCHIVOS PLE", FileDialog.LOAD);
        dialogoArchivo.setVisible(true);
        if (dialogoArchivo.getFile() != null) {
            /* Validar que se haya Seleccionado un Archivo*/
            directorio = dialogoArchivo.getDirectory();
            nombreArchivo = dialogoArchivo.getFile();
            RutaArchivo.setText(directorio + nombreArchivo);
            RutaAr = directorio + nombreArchivo;
        }


    }//GEN-LAST:event_boton_rutaActionPerformed

    public void EnableFalse() {
        TEnvio.setEnabled(false);
        TLegislatura.setEnabled(false);
        CEntidad.setEnabled(false);
        boton_ruta.setEnabled(false);
        Boton_insertar.setEnabled(false);
        botón_log_tabla.setEnabled(false);
        Combobox_proceso.setEnabled(false);
    }

    public void EnableTrue() {
        TEnvio.setEnabled(true);
        TLegislatura.setEnabled(true);
        CEntidad.setEnabled(true);
        boton_ruta.setEnabled(true);
        Boton_insertar.setEnabled(true);
        botón_log_tabla.setEnabled(true);
        Combobox_proceso.setEnabled(true);
    }


    private void Button_Insertar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Insertar
        String TABLA_SELECCIONADA = Combobox_proceso.getSelectedItem().toString();
        List<Periodo> listaPeriodos = new ArrayList<>();         
        ItemCombo seleccionado = (ItemCombo) CAño.getSelectedItem();
        int año_seleccionado = seleccionado.getValor();
        Valores();//asigna valores a a entidad, legislatura y envío.
        System.out.println("RUTA: " + RutaAr);
    if (CheckBox_1PO.isSelected()) listaPeriodos.add(Periodo.PRIMER_ORDINARIO);
    if (CheckBox_1PR.isSelected()) listaPeriodos.add(Periodo.PRIMER_RECESO);
    if (CheckBox_2PO.isSelected()) listaPeriodos.add(Periodo.SEGUNDO_ORDINARIO);
    if (CheckBox_2PR.isSelected()) listaPeriodos.add(Periodo.SEGUNDO_RECESO);
    if (CheckBox_3PO.isSelected()) listaPeriodos.add(Periodo.TERCER_ORDINARIO);
    if (CheckBox_3PR.isSelected()) listaPeriodos.add(Periodo.TERCER_RECESO);
       
    if (listaPeriodos.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Debe seleccionar al menos un periodo");
        return;
    }
 
        //Asegurar que se haya seleccionado formato de archivo
        if (!RadioButtonCsv.isSelected() && !RadioButtonXlsx.isSelected()) {
            //JOptionPane.showMessageDialog(null, "FAVOR DE SELECCIONAR EL FORMATO DEL ARCHIVO (CSV O XLSX).");
            JOptionPane.showMessageDialog( null,"<html>FAVOR DE SELECCIONAR EL FORMATO DEL ARCHIVO (<b>CSV</b> O <b>XLSX</b>).</html>","Formato requerido",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Validar ruta de archivo
        if (RutaArchivo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor de seleccionar archivo");
            return;
        }

        // Validar envío y legislatura
        if (Envio.isEmpty() || Legislatura.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor de capturar Envío y Legislatura");
            return;
        }

        ///ELIMINA DATOS DE LA TABLA TEMPORAL
        Querys Q = new Querys();
        Estatus = Q.Estatus(Entidad, Legislatura, Envio);

        if (Estatus.equals("Liberado")) {
            JOptionPane.showMessageDialog(
                    null,
                    "La información se encuentra en estatus liberado\nEntidad: " + Entidad
                    + " Leg: " + Legislatura + " Envío: " + Envio
            );
            return;
        }

        
           

            // ===== HILO =====
            Thread thread = new Thread(() -> {

                ProgressBar_PLE_TMP.setVisible(true);
                Progressline.setVisible(true);
                Label_Progressline.setVisible(true);
                ProgressBar_PLE_TMP.setValue(0);
                try {

                    if (RadioButtonCsv.isSelected()) {
                        System.out.println("botón csv");
                         valida_info_correcta_Generales valida_gral = new  valida_info_correcta_Generales();                                               
                         // Validar año y periodo int anioApp,List<Periodo> periodosApp,String rutaExcel,String tipo_archivo)
                            if (!valida_gral.valida_info_correcta_Generales(año_seleccionado, listaPeriodos, RutaAr, "CSV")) {
                               JOptionPane.showMessageDialog(null, "Año, legislatura y/o periodo seleccionados no coinciden con los datos reportados en Excel. FAVOR DE REVISAR LA INFORMACIÓN");
                               return;
                           }
                        if (TABLA_SELECCIONADA.equals("ALL_TABLES")) {
                             EliminaTMP Elimina = new EliminaTMP();
                             Elimina.EliminaTMP(Entidad, Envio, Legislatura, "ALL_TABLES");
                            Tmp_ple_meds1_1_CSV meds1_1 = new Tmp_ple_meds1_1_CSV();
                            Tmp_ple_meds1_2_CSV meds1_2 = new Tmp_ple_meds1_2_CSV();
                            Tmp_ple_meds1_3_CSV meds1_3 = new Tmp_ple_meds1_3_CSV();
                            Tmp_ple_meds1_4_CSV meds1_4 = new Tmp_ple_meds1_4_CSV();
                            Tmp_ple_meds1_5_CSV meds1_5 = new Tmp_ple_meds1_5_CSV();
                            Tmp_ple_meds1_6_CSV meds1_6 = new Tmp_ple_meds1_6_CSV();
                            Tmp_ple_meds1_7_CSV meds1_7 = new Tmp_ple_meds1_7_CSV();
                            Tmp_ple_meds1_8_CSV meds1_8 = new Tmp_ple_meds1_8_CSV();
                            Tmp_ple_meds1_9_CSV meds1_9 = new Tmp_ple_meds1_9_CSV();
                            try {
                                Progressline.setText("");
                                ProgressBar_PLE_TMP.setValue(3);
                                Progressline.setText("TMP_PLE_MEDS1_1");
                                meds1_1.Meds1_1_CSV(directorio + "BD_datos_generales.csv", Entidad, Envio, Legislatura, Estatus);
                                ProgressBar_PLE_TMP.setValue(34);
                                Progressline.setText("TMP_PLE_MEDS1_2");
                                meds1_2.Meds1_2_CSV(directorio + "BD_comisiones_legislativas.csv", Entidad, Envio, Legislatura, Estatus);
                                ProgressBar_PLE_TMP.setValue(41);
                                Progressline.setText("TMP_PLE_MEDS1_3");
                                meds1_3.Meds1_3_CSV(directorio + "BD_personas_legisladoras.csv", Entidad, Envio, Legislatura, Estatus);
                                ProgressBar_PLE_TMP.setValue(48);
                                Progressline.setText("TMP_PLE_MEDS1_4");
                                meds1_4.Meds1_4_CSV(directorio + "BD_personal_apoyo.csv", Entidad, Envio, Legislatura, Estatus);
                                ProgressBar_PLE_TMP.setValue(56);
                                Progressline.setText("TMP_PLE_MEDS1_5");
                                meds1_5.Meds1_5_CSV(directorio + "BD_iniciativas.csv", Entidad, Envio, Legislatura, Estatus);
                                Progressline.setText("TMP_PLE_MEDS1_6");
                                ProgressBar_PLE_TMP.setValue(65);
                                meds1_6.Meds1_6_CSV(directorio + "BD_iniciativas_urgente_obvia.csv", Entidad, Envio, Legislatura, Estatus);
                                ProgressBar_PLE_TMP.setValue(72);
                                Progressline.setText("TMP_PLE_MEDS1_7");
                                meds1_7.Meds1_7_CSV(directorio + "BD_juicios_politicos.csv", Entidad, Envio, Legislatura, Estatus);
                                ProgressBar_PLE_TMP.setValue(80);
                                Progressline.setText("TMP_PLE_MEDS1_8");
                                meds1_8.Meds1_8_CSV(directorio + "BD_declaraciones_procedencias.csv", Entidad, Envio, Legislatura, Estatus);
                                ProgressBar_PLE_TMP.setValue(90);
                                Progressline.setText("TMP_PLE_MEDS1_9");
                                meds1_9.Meds1_9_CSV(directorio + "BD_comparecencias.csv", Entidad, Envio, Legislatura, Estatus);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada a TMP, favor de revisar pantalla errores de insert");
                            } catch (Exception ex) {
                                Logger.getLogger(Integrar_TMP.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        if (!"ALL_TABLES".equals(TABLA_SELECCIONADA)) {
                            try {
                                EliminaTMP elimina = new EliminaTMP();
                                elimina.EliminaTMP(Entidad, Envio, Legislatura, TABLA_SELECCIONADA);

                                Progressline.setText("");
                                ProgressBar_PLE_TMP.setValue(1);
                                Progressline.setText(TABLA_SELECCIONADA);

                                switch (TABLA_SELECCIONADA) {

                                    case "TMP_PLE_MEDS1_1":
                                        new Tmp_ple_meds1_1_CSV().Meds1_1_CSV(directorio + "BD_datos_generales.csv",Entidad, Envio, Legislatura, Estatus);
                                        break;

                                    case "TMP_PLE_MEDS1_2":
                                        new Tmp_ple_meds1_2_CSV().Meds1_2_CSV(directorio + "BD_comisiones_legislativas.csv",Entidad, Envio, Legislatura, Estatus);
                                        break;

                                    case "TMP_PLE_MEDS1_3":
                                        new Tmp_ple_meds1_3_CSV().Meds1_3_CSV(directorio + "BD_personas_legisladoras.csv",Entidad, Envio, Legislatura, Estatus);
                                        break;
                                    case "TMP_PLE_MEDS1_4":
                                        new Tmp_ple_meds1_4_CSV().Meds1_4_CSV(directorio + "BD_personal_apoyo.csv",Entidad, Envio, Legislatura, Estatus);
                                        break;

                                    case "TMP_PLE_MEDS1_5":
                                        new Tmp_ple_meds1_5_CSV().Meds1_5_CSV(directorio + "BD_iniciativas.csv",Entidad, Envio, Legislatura, Estatus);
                                        break;
                                    
                                    case "TMP_PLE_MEDS1_6":
                                        new Tmp_ple_meds1_6_CSV().Meds1_6_CSV(directorio + "BD_iniciativas_urgente_obvia.csv",Entidad, Envio, Legislatura, Estatus);
                                        break;

                                    case "TMP_PLE_MEDS1_7":
                                        new Tmp_ple_meds1_7_CSV().Meds1_7_CSV(directorio + "BD_juicios_politicos.csv",Entidad, Envio, Legislatura, Estatus);
                                        break;

                                    case "TMP_PLE_MEDS1_8":
                                        new Tmp_ple_meds1_8_CSV().Meds1_8_CSV(directorio + "BD_declaraciones_procedencias.csv",Entidad, Envio, Legislatura, Estatus);
                                        break;

                                    case "TMP_PLE_MEDS1_9":
                                        new Tmp_ple_meds1_9_CSV().Meds1_9_CSV(directorio + "BD_comparecencias.csv",Entidad, Envio, Legislatura, Estatus);
                                        break;

                                    default:
                                        JOptionPane.showMessageDialog(null,
                                                "Tabla no soportada: " + TABLA_SELECCIONADA);
                                        return;
                                }
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null,  "Información insertada a TMP, favor de revisar pantalla errores de insert");
                            } catch (SQLException ex) {
                                Logger.getLogger(Integrar_TMP.class.getName()).log(Level.SEVERE, "Error al eliminar TMP", ex);
                            } catch (Exception ex) {
                                Logger.getLogger(Integrar_TMP.class.getName()).log(Level.SEVERE, "Error al procesar CSV", ex);
                            } finally {
                                EnableTrue();
                                ProgressBar_PLE_TMP.setVisible(false);
                                Progressline.setVisible(false);
                                Label_Progressline.setVisible(false);
                            }
                        }

                    } else {
                        System.out.println("botón xlsx");
                        valida_info_correcta_Generales valida_gral = new  valida_info_correcta_Generales();
                        
                        // Validar año y periodo int anioApp,List<Periodo> periodosApp,String rutaExcel,String tipo_archivo)
                            if (!valida_gral.valida_info_correcta_Generales(año_seleccionado, listaPeriodos, RutaAr, "XLSX")) {
                               JOptionPane.showMessageDialog(null, "Año y/o periodo seleccionados no coinciden con los datos reportados en Excel");
                               return;
                           }

                        EnableFalse();                       
                        Tmp_ple_meds1_1 ple_meds1_1 = new Tmp_ple_meds1_1();
                        Tmp_ple_meds1_1A ple_meds1_1A = new Tmp_ple_meds1_1A();
                        Tmp_ple_meds1_1B ple_meds1_1B = new Tmp_ple_meds1_1B();
                        Tmp_ple_meds1_1C ple_meds1_1C = new Tmp_ple_meds1_1C();
                        Tmp_ple_meds1_1D ple_meds1_1D = new Tmp_ple_meds1_1D();
                        Tmp_ple_meds1_2 ple_meds1_2 = new Tmp_ple_meds1_2();
                        Tmp_ple_meds1_3 ple_meds1_3 = new Tmp_ple_meds1_3();
                        Tmp_ple_meds1_4 ple_meds1_4 = new Tmp_ple_meds1_4();
                        Tmp_ple_meds1_5 ple_meds1_5 = new Tmp_ple_meds1_5();
                        Tmp_ple_meds1_6 ple_meds1_6 = new Tmp_ple_meds1_6();
                        Tmp_ple_meds1_7 ple_meds1_7 = new Tmp_ple_meds1_7();
                        Tmp_ple_meds1_8 ple_meds1_8 = new Tmp_ple_meds1_8();
                        Tmp_ple_meds1_9 ple_meds1_9 = new Tmp_ple_meds1_9();

                        try {

                            if (Procedure.equals("ALL_TABLES")) {
                             EliminaTMP Elimina = new EliminaTMP();
                             Elimina.EliminaTMP(Entidad, Envio, Legislatura, "ALL_TABLES"); 
                                Progressline.setText("");
                                ProgressBar_PLE_TMP.setValue(3);
                                Progressline.setText("TMP_PLE_MEDS1_1");
                                ple_meds1_1.In_Tmp_ple_meds1_1(Entidad, Envio, Legislatura, CEstatus.getSelectedItem().toString());
                                ProgressBar_PLE_TMP.setValue(7);
                                Progressline.setText("TMP_PLE_MEDS1_1A");
                                ple_meds1_1A.in_Tmp_ple_meds1_1A(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(14);
                                Progressline.setText("TMP_PLE_MEDS1_1B");
                                ple_meds1_1B.Tmp_ple_meds1_1B(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(21);
                                Progressline.setText("TMP_PLE_MEDS1_1C");
                                ple_meds1_1C.Tmp_ple_meds1_1C(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(27);
                                Progressline.setText("TMP_PLE_MEDS1_1D");
                                ple_meds1_1D.Tmp_ple_meds1_1D(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(34);
                                Progressline.setText("TMP_PLE_MEDS1_2");
                                ple_meds1_2.Tmp_ple_meds1_2(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(41);
                                Progressline.setText("TMP_PLE_MEDS1_3");
                                ple_meds1_3.Tmp_ple_meds1_3(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(48);
                                Progressline.setText("TMP_PLE_MEDS1_4");
                                ple_meds1_4.Tmp_ple_meds1_4(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(56);
                                Progressline.setText("TMP_PLE_MEDS1_5");
                                ple_meds1_5.Tmp_ple_meds1_5(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(64);
                                Progressline.setText("TMP_PLE_MEDS1_6");
                                ple_meds1_6.Tmp_ple_meds1_6(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(72);
                                Progressline.setText("TMP_PLE_MEDS1_7");
                                ple_meds1_7.Tmp_ple_meds1_7(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(80);
                                Progressline.setText("TMP_PLE_MEDS1_8");
                                ple_meds1_8.Tmp_ple_meds1_8(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(90);
                                Progressline.setText("TMP_PLE_MEDS1_9");
                                ple_meds1_9.Tmp_ple_meds1_9(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada a TMP, favor de revisar pantalla errores de insert");

                            }
                            if (Procedure.equals("TMP_PLE_MEDS1_1")) {
                                 EliminaTMP Elimina = new EliminaTMP();
                                 Elimina.EliminaTMP(Entidad, Envio, Legislatura, "TMP_PLE_MEDS1_1");
                                ProgressBar_PLE_TMP.setValue(15);
                                ple_meds1_1.In_Tmp_ple_meds1_1(Entidad, Envio, Legislatura, CEstatus.getSelectedItem().toString());
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada, favor de revisar pantalla errores de insert");
                            }
                            if (Procedure.equals("TMP_PLE_MEDS1_1A")) {
                                EliminaTMP Elimina = new EliminaTMP();
                                 Elimina.EliminaTMP(Entidad, Envio, Legislatura, "TMP_PLE_MEDS1_1A");
                                ProgressBar_PLE_TMP.setValue(15);
                                ple_meds1_1A.in_Tmp_ple_meds1_1A(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada, favor de revisar pantalla errores de insert");
                            }
                            if (Procedure.equals("TMP_PLE_MEDS1_1B")) {
                                 EliminaTMP Elimina = new EliminaTMP();
                                 Elimina.EliminaTMP(Entidad, Envio, Legislatura, "TMP_PLE_MEDS1_1B");
                                ProgressBar_PLE_TMP.setValue(15);
                                ple_meds1_1B.Tmp_ple_meds1_1B(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada, favor de revisar pantalla errores de insert");
                            }
                            if (Procedure.equals("TMP_PLE_MEDS1_1C")) {
                                EliminaTMP Elimina = new EliminaTMP();
                                 Elimina.EliminaTMP(Entidad, Envio, Legislatura, "TMP_PLE_MEDS1_1C");
                                ProgressBar_PLE_TMP.setValue(15);
                                ple_meds1_1C.Tmp_ple_meds1_1C(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada, favor de revisar pantalla errores de insert");
                            }
                            if (Procedure.equals("TMP_PLE_MEDS1_1D")) {
                                EliminaTMP Elimina = new EliminaTMP();
                                 Elimina.EliminaTMP(Entidad, Envio, Legislatura, "TMP_PLE_MEDS1_1D");
                                ProgressBar_PLE_TMP.setValue(15);
                                ple_meds1_1D.Tmp_ple_meds1_1D(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada, favor de revisar pantalla errores de insert");
                            }
                            if (Procedure.equals("TMP_PLE_MEDS1_2")) {
                                EliminaTMP Elimina = new EliminaTMP();
                                 Elimina.EliminaTMP(Entidad, Envio, Legislatura, "TMP_PLE_MEDS1_2");
                                ProgressBar_PLE_TMP.setValue(15);
                                ple_meds1_2.Tmp_ple_meds1_2(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada, favor de revisar pantalla errores de insert");
                            }
                            if (Procedure.equals("TMP_PLE_MEDS1_3")) {
                                EliminaTMP Elimina = new EliminaTMP();
                                 Elimina.EliminaTMP(Entidad, Envio, Legislatura, "TMP_PLE_MEDS1_3");
                                ProgressBar_PLE_TMP.setValue(15);
                                ple_meds1_3.Tmp_ple_meds1_3(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada, favor de revisar pantalla errores de insert");
                            }
                            if (Procedure.equals("TMP_PLE_MEDS1_4")) {
                                EliminaTMP Elimina = new EliminaTMP();
                                 Elimina.EliminaTMP(Entidad, Envio, Legislatura, "TMP_PLE_MEDS1_4");
                                ProgressBar_PLE_TMP.setValue(15);
                                ple_meds1_4.Tmp_ple_meds1_4(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada, favor de revisar pantalla errores de insert");
                            }
                            if (Procedure.equals("TMP_PLE_MEDS1_5")) {
                                 EliminaTMP Elimina = new EliminaTMP();
                                 Elimina.EliminaTMP(Entidad, Envio, Legislatura, "TMP_PLE_MEDS1_5");
                                ProgressBar_PLE_TMP.setValue(15);
                                ple_meds1_5.Tmp_ple_meds1_5(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada, favor de revisar pantalla errores de insert");
                            }
                            if (Procedure.equals("TMP_PLE_MEDS1_6")) {
                                EliminaTMP Elimina = new EliminaTMP();
                                 Elimina.EliminaTMP(Entidad, Envio, Legislatura, "TMP_PLE_MEDS1_6");
                                ProgressBar_PLE_TMP.setValue(15);
                                ple_meds1_6.Tmp_ple_meds1_6(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada, favor de revisar pantalla errores de insert");
                            }
                            if (Procedure.equals("TMP_PLE_MEDS1_7")) {
                                EliminaTMP Elimina = new EliminaTMP();
                                 Elimina.EliminaTMP(Entidad, Envio, Legislatura, "TMP_PLE_MEDS1_7");
                                ProgressBar_PLE_TMP.setValue(15);
                                ple_meds1_7.Tmp_ple_meds1_7(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada, favor de revisar pantalla errores de insert");
                            }
                            if (Procedure.equals("TMP_PLE_MEDS1_8")) {
                                EliminaTMP Elimina = new EliminaTMP();
                                 Elimina.EliminaTMP(Entidad, Envio, Legislatura, "TMP_PLE_MEDS1_8");
                                ProgressBar_PLE_TMP.setValue(15);
                                ple_meds1_8.Tmp_ple_meds1_8(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada, favor de revisar pantalla errores de insert");
                            }
                            if (Procedure.equals("TMP_PLE_MEDS1_9")) {
                                 EliminaTMP Elimina = new EliminaTMP();
                                 Elimina.EliminaTMP(Entidad, Envio, Legislatura, "TMP_PLE_MEDS1_9");
                                ProgressBar_PLE_TMP.setValue(15);
                                ple_meds1_9.Tmp_ple_meds1_9(Entidad, Envio, Legislatura);
                                ProgressBar_PLE_TMP.setValue(100);
                                JOptionPane.showMessageDialog(null, "Información insertada, favor de revisar pantalla errores de insert");
                            }
                            Label_Progressline.setVisible(false);
                            ProgressBar_PLE_TMP.setVisible(false);
                            Progressline.setVisible(false);
                            EnableTrue();
                        } catch (Exception ex) {
                            Logger.getLogger(Integrar_TMP.class.getName()).log(Level.SEVERE, null, ex);
                        } finally {
                            EnableTrue();
                            ProgressBar_PLE_TMP.setVisible(false);
                            Progressline.setVisible(false);
                            Label_Progressline.setVisible(false);
                        }
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Integrar_TMP.class.getName()).log(Level.SEVERE, null, ex);
                }
            });

            thread.start();

        


    }//GEN-LAST:event_Button_Insertar

    private void botón_log_tablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botón_log_tablaActionPerformed
        // TODO add your handling code here:
        Valores();
        if (!TEnvio.getText().equals("") && !TLegislatura.getText().equals("") && !CEntidad.getSelectedItem().toString().equals("")) {
            if (!ventanaAbierta) {
                ventanaAbierta = true;
                Errores_InsertTMP Errores = new Errores_InsertTMP();
                Errores.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Ventana Errores de insert abierta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Favor de capturar Entidad,Envío y Legislatura");
        }


    }//GEN-LAST:event_botón_log_tablaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);

    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Label_Progressline.setVisible(false);
        ProgressBar_PLE_TMP.setVisible(false);
        RutaArchivo.setEnabled(false);
        Progressline.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void RadioButtonCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonCsvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonCsvActionPerformed

    private void RadioButtonXlsxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonXlsxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonXlsxActionPerformed

    private void Combobox_procesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combobox_procesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combobox_procesoActionPerformed

    private void RutaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutaArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RutaArchivoActionPerformed

    private void CheckBox_1POActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_1POActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox_1POActionPerformed

    private void CAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAñoActionPerformed

    private void CheckBox_1PRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_1PRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox_1PRActionPerformed

    private void CheckBox_2POActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_2POActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox_2POActionPerformed

    private void CheckBox_3PRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_3PRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox_3PRActionPerformed

    private void CheckBox_2PRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_2PRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox_2PRActionPerformed

    private void CheckBox_3POActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_3POActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox_3POActionPerformed

    private void CEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEntidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEntidadActionPerformed

    public void Valores() {
        Entidad = CEntidad.getSelectedItem().toString();
        Envio = TEnvio.getText();
        Legislatura = TLegislatura.getText();
        Procedure = Combobox_proceso.getSelectedItem().toString();       
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Integrar_TMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Integrar_TMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Integrar_TMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Integrar_TMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Integrar_TMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_insertar;
    private javax.swing.JComboBox CAño;
    private javax.swing.JComboBox CEntidad;
    private javax.swing.JComboBox CEstatus;
    private javax.swing.JCheckBox CheckBox_1PO;
    private javax.swing.JCheckBox CheckBox_1PR;
    private javax.swing.JCheckBox CheckBox_2PO;
    private javax.swing.JCheckBox CheckBox_2PR;
    private javax.swing.JCheckBox CheckBox_3PO;
    private javax.swing.JCheckBox CheckBox_3PR;
    private javax.swing.JComboBox Combobox_proceso;
    private javax.swing.JLabel Label_Estatus;
    private javax.swing.JLabel Label_Legislatura;
    private javax.swing.JLabel Label_Logo;
    private javax.swing.JLabel Label_Periodo;
    private javax.swing.JLabel Label_Procedure;
    private javax.swing.JLabel Label_Progressline;
    private javax.swing.JLabel Label_RutaArchivo;
    private javax.swing.JLabel Label_Year;
    private javax.swing.JLabel Label_entidad;
    private javax.swing.JLabel Label_envio;
    private javax.swing.JLabel Label_formatoarchivo;
    private javax.swing.JPanel Panel_PLE_ENCABEZADO;
    private javax.swing.JPanel Panel_PLE_insertarTMP;
    private javax.swing.JPanel Panel_Verde;
    private javax.swing.JProgressBar ProgressBar_PLE_TMP;
    private javax.swing.JLabel Progressline;
    private javax.swing.JRadioButton RadioButtonCsv;
    private javax.swing.JRadioButton RadioButtonXlsx;
    private javax.swing.JTextField RutaArchivo;
    private javax.swing.JTextField TEnvio;
    private javax.swing.JTextField TLegislatura;
    private javax.swing.JButton boton_ruta;
    private javax.swing.JButton botón_log_tabla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
