/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas_PLE;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import mx.org.inegi.QuerysGeneral.PLE.Querys;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Justificaciones extends javax.swing.JFrame {
    
    public static String DENTIDAD,DLEGISLATURA,DENVIO,DTABLA,DID_TABLA,DCAMPO,DVALOR_CAMPO,DOBSERVACION,DJUSTIFICACION,DVALOR_INSERTADO,DID_UNIQUE;
    public static boolean VNuevo=false;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Justificaciones.class.getName());

    /**
     * Creates new form Justificaciones
     */
    public Justificaciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Titulo = new javax.swing.JLabel();
        Label_logo = new javax.swing.JLabel();
        Banner_verde = new javax.swing.JPanel();
        LabelEntidad = new javax.swing.JLabel();
        CEntidad = new javax.swing.JComboBox();
        LabelLegislatura = new javax.swing.JLabel();
        CLegislatura = new javax.swing.JComboBox();
        LabelEnvio = new javax.swing.JLabel();
        TEnvio = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Label_Titulo.setBackground(new java.awt.Color(0, 0, 102));
        Label_Titulo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Label_Titulo.setText("Poderes Legislativos Estatales");

        Label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo CNG.png"))); // NOI18N

        Banner_verde.setBackground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout Banner_verdeLayout = new javax.swing.GroupLayout(Banner_verde);
        Banner_verde.setLayout(Banner_verdeLayout);
        Banner_verdeLayout.setHorizontalGroup(
            Banner_verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Banner_verdeLayout.setVerticalGroup(
            Banner_verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        LabelEntidad.setText("Entidad:");

        CEntidad.setToolTipText("");
        CEntidad.addActionListener(this::CEntidadActionPerformed);

        LabelLegislatura.setText("Legislatura:");

        CLegislatura.addActionListener(this::CLegislaturaActionPerformed);

        LabelEnvio.setText("Envio:");

        TEnvio.addActionListener(this::TEnvioActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tabla", "Id_tabla", "Campo", "Valor Campo", "Observacion", "Justificacion", "Valor insertado", "id_unique"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/download.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refresh.png"))); // NOI18N
        jButton2.setText("Act.");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Banner_verde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelEntidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelLegislatura)
                            .addComponent(CLegislatura, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelEnvio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1108, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Label_Titulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Titulo)
                    .addComponent(Label_logo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Banner_verde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLegislatura, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CLegislatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Asigna_Valores(){
        ValidaPLE val=new ValidaPLE();
        CEntidad.addItem(val.entidad);
        CLegislatura.addItem(val.legislatura);
        TEnvio.addItem(val.envio);
    }
    
    public void Muestra_tabla() {
    Querys Q = new Querys();
    ArrayList<String[]> datos = Q.Justificaciones(
            CEntidad.getSelectedItem().toString(),
            CLegislatura.getSelectedItem().toString(),
            TEnvio.getSelectedItem().toString());
    String[] columnas = {
        "TABLA",
        "ID_TABLA",
        "CAMPO",
        "VALOR_CAMPO",
        "OBSERVACION",
        "JUSTIFICACION",
        "VALOR_INSERTADO",
        "ID_UNIQUE"
    };
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Ninguna celda será editable
        }
    };
    for (String[] fila : datos) {
        modelo.addRow(fila);
    }
    jTable1.setModel(modelo);
     // Ocultar la columna ID_UNIQUE
    jTable1.getColumnModel().getColumn(7).setMinWidth(0);
    jTable1.getColumnModel().getColumn(7).setMaxWidth(0);
    jTable1.getColumnModel().getColumn(7).setWidth(0);
    jTable1.getColumnModel().getColumn(7).setPreferredWidth(0);
}
    
    private void CEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEntidadActionPerformed
       
        
    }//GEN-LAST:event_CEntidadActionPerformed

    private void CLegislaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLegislaturaActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_CLegislaturaActionPerformed

    private void TEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEnvioActionPerformed

    }//GEN-LAST:event_TEnvioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       Asigna_Valores();
       Muestra_tabla();
      
       
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        VNuevo=false;
        int selectedRowIndex = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (evt.getClickCount() == 2) {
            DENTIDAD = CEntidad.getSelectedItem().toString();
            DLEGISLATURA = CLegislatura.getSelectedItem().toString();
            DENVIO = TEnvio.getSelectedItem().toString();
            Object valor;
            valor = model.getValueAt(selectedRowIndex, 0);
            if (valor != null) {
                DTABLA = valor.toString();
            } else {
                DTABLA = "";
            }
            valor = model.getValueAt(selectedRowIndex, 1);
            if (valor != null) {
                DID_TABLA = valor.toString();
            } else {
                DID_TABLA = "";
            }
            valor = model.getValueAt(selectedRowIndex, 2);
            if (valor != null) {
                DCAMPO = valor.toString();
            } else {
                DCAMPO = "";
            }
            valor = model.getValueAt(selectedRowIndex, 3);
            if (valor != null) {
                DVALOR_CAMPO = valor.toString();
            } else {
                DVALOR_CAMPO = "";
            }
            valor = model.getValueAt(selectedRowIndex, 4);
            if (valor != null) {
                DOBSERVACION = valor.toString();
            } else {
                DOBSERVACION = "";
            }
            valor = model.getValueAt(selectedRowIndex, 5);
            if (valor != null) {
                DJUSTIFICACION = valor.toString();
            } else {
                DJUSTIFICACION = "";
            }
            valor = model.getValueAt(selectedRowIndex, 6);
            if (valor != null) {
                DVALOR_INSERTADO = valor.toString();
            } else {
                DVALOR_INSERTADO = "";
            }
            valor = model.getValueAt(selectedRowIndex, 7);
            if (valor != null) {
                DID_UNIQUE = valor.toString();
            } else {
                DID_UNIQUE = "";
            }
            Justificaciones_Cambios CCambio = new Justificaciones_Cambios();
            CCambio.setVisible(true);
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VNuevo=true;
        DENTIDAD = CEntidad.getSelectedItem().toString();
        DLEGISLATURA = CLegislatura.getSelectedItem().toString();
        DENVIO = TEnvio.getSelectedItem().toString();
        Justificaciones_Cambios camb=new Justificaciones_Cambios();
        camb.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Muestra_tabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Justificaciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner_verde;
    private javax.swing.JComboBox CEntidad;
    private javax.swing.JComboBox CLegislatura;
    private javax.swing.JLabel LabelEntidad;
    private javax.swing.JLabel LabelEnvio;
    private javax.swing.JLabel LabelLegislatura;
    private javax.swing.JLabel Label_Titulo;
    private javax.swing.JLabel Label_logo;
    private javax.swing.JComboBox TEnvio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
