/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas_PLE;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import mx.org.inegi.QuerysGeneral.PLE.Querys;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Justificaciones_Cambios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Justificaciones_Cambios.class.getName());
    Querys Q=new Querys();

    /**
     * Creates new form Justificaciones_Cambios
     */
    public Justificaciones_Cambios() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
          SwingUtilities.invokeLater(() -> {
        TID_TABLA.requestFocusInWindow();
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Titulo = new javax.swing.JLabel();
        Label_logo = new javax.swing.JLabel();
        Banner_verde = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TENTIDAD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TLEGISLATURA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TENVIO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TID_TABLA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TVALOR_CAMPO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TOBSERVACION = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TJUSTIFICACION = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        TVALORINSERTADO = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TCAMPO = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        TID = new javax.swing.JTextField();
        TTABLA = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Label_Titulo.setBackground(new java.awt.Color(0, 0, 102));
        Label_Titulo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Label_Titulo.setText("Poderes Legislativos Estatales");

        Label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo CNG.png"))); // NOI18N

        Banner_verde.setBackground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout Banner_verdeLayout = new javax.swing.GroupLayout(Banner_verde);
        Banner_verde.setLayout(Banner_verdeLayout);
        Banner_verdeLayout.setHorizontalGroup(
            Banner_verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Banner_verdeLayout.setVerticalGroup(
            Banner_verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Entidad");

        TENTIDAD.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Legislatura");

        TLEGISLATURA.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Id_envio");

        TENVIO.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tabla");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ID_Tabla");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Campo");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Valor_campo");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Observacion");

        TOBSERVACION.setColumns(20);
        TOBSERVACION.setRows(5);
        jScrollPane1.setViewportView(TOBSERVACION);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Justificacion");

        TJUSTIFICACION.setColumns(20);
        TJUSTIFICACION.setRows(5);
        jScrollPane2.setViewportView(TJUSTIFICACION);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Valor insertado");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CREATE_TEPJF.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borrar.png"))); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualiza.svg.jpg"))); // NOI18N
        jButton3.setText("Actualizar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        TCAMPO.setColumns(20);
        TCAMPO.setRows(5);
        jScrollPane3.setViewportView(TCAMPO);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("id_justificacion");

        TID.setEditable(false);

        TTABLA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DATOS GENERALES (TR_PLE_MEDS1_1A)", "DATOS GENERALES (TR_PLE_MEDS1_1B)", "DATOS GENERALES (TR_PLE_MEDS1_1C)", "DATOS GENERALES (TR_PLE_MEDS1_1D)", "COMISIONES LEGISLATIVAS (TR_PLE_MEDS1_2)", "PERSONAS LEGISLADORAS (TR_PLE_MEDS1_3)", "PERSONAL APOYO (TR_PLE_MEDS1_4)", "INICIATIVAS (TR_PLE_MEDS1_5)", "INICIATIVA URGENTE OBVIA (TR_PLE_MEDS1_6)", "JUICIOS POLITICOS (TR_PLE_MEDS1_7)", "DECLARACIONES PROCEDENCIA (TR_PLE_MEDS1_8)", "COMPARECENCIAS (TR_PLE_MEDS1_9)" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TTABLA, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TID_TABLA))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Banner_verde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 1123, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Label_Titulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Label_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TVALOR_CAMPO))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TENTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TLEGISLATURA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TENVIO, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TVALORINSERTADO, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Titulo)
                    .addComponent(Label_logo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Banner_verde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TENTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TLEGISLATURA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TENVIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TTABLA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TID_TABLA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(TVALOR_CAMPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(77, 77, 77))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(TVALORINSERTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Justificaciones Jus=new Justificaciones();
       if (Jus.VNuevo==false)
       {
        TENTIDAD.setText(Jus.DENTIDAD);
        TLEGISLATURA.setText(Jus.DLEGISLATURA);
        TENVIO.setText(Jus.DENVIO);
        TTABLA.setSelectedItem(Jus.DTABLA);
        TID_TABLA.setText(Jus.DID_TABLA);
        TCAMPO.setText(Jus.DCAMPO);
        TVALOR_CAMPO.setText(Jus.DVALOR_CAMPO);
        TOBSERVACION.setText(Jus.DOBSERVACION);
        TJUSTIFICACION.setText(Jus.DJUSTIFICACION);
        TVALORINSERTADO.setText(Jus.DVALOR_INSERTADO);
        TID.setText(Jus.DID_UNIQUE);
        jButton1.setVisible(false);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
       jLabel11.setVisible(true);
       TID.setVisible(true);
       }else{
        jLabel11.setVisible(false);
         TID.setVisible(false);
        TENTIDAD.setText(Jus.DENTIDAD);
        TLEGISLATURA.setText(Jus.DLEGISLATURA);
        TENVIO.setText(Jus.DENVIO);
        jButton1.setVisible(true);
         jButton2.setVisible(false);
        jButton3.setVisible(false);
       }
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  
       
        
    if (TENTIDAD.getText().trim().isEmpty()
        || TLEGISLATURA.getText().trim().isEmpty()
        || TENVIO.getText().trim().isEmpty()
        || TTABLA.getSelectedItem().toString().trim().isEmpty()
        || TID_TABLA.getText().trim().isEmpty()
        || TCAMPO.getText().trim().isEmpty()
        || TOBSERVACION.getText().trim().isEmpty()
        || TJUSTIFICACION.getText().trim().isEmpty())
         {  
        JOptionPane.showMessageDialog(
            this,
            "Todos los campos son obligatorios.",
            "Campos incompletos",
            JOptionPane.WARNING_MESSAGE);
    return;
    }
        int opcion = JOptionPane.showConfirmDialog(
        null,
        "¿Está seguro de que desea insertar la justificación?",
        "Confirmar inserción",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
     if (opcion == JOptionPane.YES_OPTION) {   
           if (TVALOR_CAMPO.getText().trim().isEmpty()){
           TVALOR_CAMPO.setText("NULL");
       }
       if (TVALORINSERTADO.getText().trim().isEmpty()){
           TVALORINSERTADO.setText("NULL");
       }
        Q.Inserta_Justificacion(
    TENTIDAD.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TLEGISLATURA.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TENVIO.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TTABLA.getSelectedItem().toString().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TID_TABLA.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TCAMPO.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TVALOR_CAMPO.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TOBSERVACION.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TJUSTIFICACION.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TVALORINSERTADO.getText().toUpperCase().replaceAll("[\\r\\n]+", " ")
);
        this.setVisible(false);
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:        
        if (TENTIDAD.getText().trim().isEmpty()
        || TLEGISLATURA.getText().trim().isEmpty()
        || TENVIO.getText().trim().isEmpty()
        || TTABLA.getSelectedItem().toString().trim().isEmpty()
        || TID_TABLA.getText().trim().isEmpty()
        || TCAMPO.getText().trim().isEmpty()
        || TOBSERVACION.getText().trim().isEmpty()
        || TJUSTIFICACION.getText().trim().isEmpty()) {  
        JOptionPane.showMessageDialog(
            this,
            "Todos los campos son obligatorios.",
            "Campos incompletos",
            JOptionPane.WARNING_MESSAGE);
    return;
    }       
        int opcion = JOptionPane.showConfirmDialog(
        null,
        "¿Está seguro de que desea actualizar la justificación?",
        "Confirmar inserción",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
         if (opcion == JOptionPane.YES_OPTION) {   
              if (TVALOR_CAMPO.getText().trim().isEmpty()){
           TVALOR_CAMPO.setText("NULL");
       }
       if (TVALORINSERTADO.getText().trim().isEmpty()){
           TVALORINSERTADO.setText("NULL");
       }
    Q.Actualiza_Justificacion(
    TENTIDAD.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TLEGISLATURA.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TENVIO.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TTABLA.getSelectedItem().toString().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TID_TABLA.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TCAMPO.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TVALOR_CAMPO.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TOBSERVACION.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TJUSTIFICACION.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TVALORINSERTADO.getText().toUpperCase().replaceAll("[\\r\\n]+", " ").trim(),
    TID.getText().trim()
); 
    this.setVisible(false);
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         int opcion = JOptionPane.showConfirmDialog(
        null,
        "¿Está seguro de que desea eliminar la justificación?",
        "Confirmar inserción",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
         if (opcion == JOptionPane.YES_OPTION) {   
        Q.Elimina_Justificacion(TID.getText());
        this.setVisible(false);
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Justificaciones_Cambios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner_verde;
    private javax.swing.JLabel Label_Titulo;
    private javax.swing.JLabel Label_logo;
    private javax.swing.JTextArea TCAMPO;
    private javax.swing.JTextField TENTIDAD;
    private javax.swing.JTextField TENVIO;
    private javax.swing.JTextField TID;
    private javax.swing.JTextField TID_TABLA;
    private javax.swing.JTextArea TJUSTIFICACION;
    private javax.swing.JTextField TLEGISLATURA;
    private javax.swing.JTextArea TOBSERVACION;
    private javax.swing.JComboBox<String> TTABLA;
    private javax.swing.JTextField TVALORINSERTADO;
    private javax.swing.JTextField TVALOR_CAMPO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
