/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_PLE;

import Pantallas_Menu.MenuProyectos;
import Pantallas_PLE.Integrar_TMP;
import Pantallas_PLE.Integrar_TR;
import Pantallas_PLE.ValidaPLE;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_MenuPLE = new javax.swing.JLabel();
        MenuBar_PLE = new javax.swing.JMenuBar();
        Menu_PLE = new javax.swing.JMenu();
        Menu_IntegraTMP = new javax.swing.JMenu();
        Menu_IntegraTR = new javax.swing.JMenu();
        Menu_Valida = new javax.swing.JMenu();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Label_MenuPLE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N

        Menu_PLE.setText("Menu");
        Menu_PLE.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N

        Menu_IntegraTMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Insertar.png"))); // NOI18N
        Menu_IntegraTMP.setText("Integrar TMP");
        Menu_IntegraTMP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_IntegraTMPMouseClicked(evt);
            }
        });
        Menu_PLE.add(Menu_IntegraTMP);

        Menu_IntegraTR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InsertaBD.png"))); // NOI18N
        Menu_IntegraTR.setText("Integrar TR");
        Menu_IntegraTR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_IntegraTRMouseClicked(evt);
            }
        });
        Menu_PLE.add(Menu_IntegraTR);

        Menu_Valida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BValidar.png"))); // NOI18N
        Menu_Valida.setText("Validar");
        Menu_Valida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_ValidaMouseClicked(evt);
            }
        });
        Menu_PLE.add(Menu_Valida);

        MenuBar_PLE.add(Menu_PLE);

        setJMenuBar(MenuBar_PLE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_MenuPLE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_MenuPLE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_IntegraTMPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_IntegraTMPMouseClicked
        // TODO add your handling code here:
        Integrar_TMP In_TMP= new Integrar_TMP();
        In_TMP.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_Menu_IntegraTMPMouseClicked

    private void Menu_IntegraTRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_IntegraTRMouseClicked
        // TODO add your handling code here:
        Integrar_TR TR=new Integrar_TR ();
        TR.setVisible(true);
    }//GEN-LAST:event_Menu_IntegraTRMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        MenuProyectos Pro=new MenuProyectos();
        Pro.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void Menu_ValidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_ValidaMouseClicked
        // TODO add your handling code here:
        ValidaPLE Pvalida=new ValidaPLE();
        Pvalida.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_Menu_ValidaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_MenuPLE;
    private javax.swing.JMenuBar MenuBar_PLE;
    private javax.swing.JMenu Menu_IntegraTMP;
    private javax.swing.JMenu Menu_IntegraTR;
    private javax.swing.JMenu Menu_PLE;
    private javax.swing.JMenu Menu_Valida;
    // End of variables declaration//GEN-END:variables
}
