/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_PLE;

import static Pantallas_PLE.Integrar_TR.Entidad;
import static Pantallas_PLE.Integrar_TR.Envio;
import static Pantallas_PLE.Integrar_TR.Legislatura;
import ValidacionesPle.QuerysValPLE.QGEN;
import ValidacionesPle.ValPLE;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.org.inegi.QuerysGeneral.PLE.Querys;

/**
 *
 * @author ANTONIO.CORIA
 */
public class ValidaPLE extends javax.swing.JFrame {

    /**
     *
     * Creates new form ValidaPLE
     */
    public static String entidad = "", legislatura = "", envio = "", Nomentidad = "", envio_anterior = "";
    ArrayList<String[]> ArrayEnvio;

    public ValidaPLE() {
        initComponents();
        this.setLocationRelativeTo(null);
        // this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO

    }

    public void valores() {
        entidad = CEntidad.getSelectedItem().toString().trim();
        Nomentidad = LEntidad.getText().trim();
        legislatura = CLegislatura.getSelectedItem().toString();
        envio = TEnvio.getSelectedItem().toString().trim();
        envio_anterior = TEnvio_anterior.getSelectedItem().toString().trim();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_PLE_LOGO = new javax.swing.JPanel();
        Label_logo = new javax.swing.JLabel();
        Banner_verde = new javax.swing.JPanel();
        Label_Titulo = new javax.swing.JLabel();
        Panel_PLE = new javax.swing.JPanel();
        LabelEntidad = new javax.swing.JLabel();
        CEntidad = new javax.swing.JComboBox();
        LabelLegislatura = new javax.swing.JLabel();
        LabelEnvio = new javax.swing.JLabel();
        TEnvio = new javax.swing.JComboBox();
        Btn_Validar = new javax.swing.JToggleButton();
        LEntidad = new javax.swing.JLabel();
        TEnvio_anterior = new javax.swing.JComboBox();
        LabelEnvioAnterior = new javax.swing.JLabel();
        CLegislatura = new javax.swing.JComboBox();
        Liberar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Panel_PLE_LOGO.setBackground(new java.awt.Color(255, 255, 255));

        Label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo CNG.png"))); // NOI18N

        Banner_verde.setBackground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout Banner_verdeLayout = new javax.swing.GroupLayout(Banner_verde);
        Banner_verde.setLayout(Banner_verdeLayout);
        Banner_verdeLayout.setHorizontalGroup(
            Banner_verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Banner_verdeLayout.setVerticalGroup(
            Banner_verdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        Label_Titulo.setBackground(new java.awt.Color(0, 0, 102));
        Label_Titulo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Label_Titulo.setText("Poderes Legislativos Estatales");

        javax.swing.GroupLayout Panel_PLE_LOGOLayout = new javax.swing.GroupLayout(Panel_PLE_LOGO);
        Panel_PLE_LOGO.setLayout(Panel_PLE_LOGOLayout);
        Panel_PLE_LOGOLayout.setHorizontalGroup(
            Panel_PLE_LOGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Banner_verde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PLE_LOGOLayout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(Label_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        Panel_PLE_LOGOLayout.setVerticalGroup(
            Panel_PLE_LOGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PLE_LOGOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_PLE_LOGOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_PLE_LOGOLayout.createSequentialGroup()
                        .addComponent(Label_Titulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Banner_verde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel_PLE.setBackground(new java.awt.Color(255, 255, 255));
        Panel_PLE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelEntidad.setText("Entidad:");

        CEntidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));
        CEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEntidadActionPerformed(evt);
            }
        });

        LabelLegislatura.setText("Legislatura:");

        LabelEnvio.setText("Envio:");

        TEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEnvioActionPerformed(evt);
            }
        });

        Btn_Validar.setText("Validar");
        Btn_Validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ValidarActionPerformed(evt);
            }
        });

        LEntidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        TEnvio_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEnvio_anteriorActionPerformed(evt);
            }
        });

        LabelEnvioAnterior.setText("Envio anterior:");

        CLegislatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLegislaturaActionPerformed(evt);
            }
        });

        Liberar.setBackground(new java.awt.Color(175, 207, 144));
        Liberar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Liberar.setText("Liberar");
        Liberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiberarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_PLELayout = new javax.swing.GroupLayout(Panel_PLE);
        Panel_PLE.setLayout(Panel_PLELayout);
        Panel_PLELayout.setHorizontalGroup(
            Panel_PLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PLELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_PLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PLELayout.createSequentialGroup()
                        .addGroup(Panel_PLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelEntidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_PLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelLegislatura)
                            .addComponent(CLegislatura, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(Panel_PLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_PLELayout.createSequentialGroup()
                                .addComponent(LabelEnvio)
                                .addGap(18, 18, 18)
                                .addComponent(LabelEnvioAnterior))
                            .addGroup(Panel_PLELayout.createSequentialGroup()
                                .addComponent(TEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TEnvio_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(Panel_PLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Liberar, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(Btn_Validar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(LEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_PLELayout.setVerticalGroup(
            Panel_PLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PLELayout.createSequentialGroup()
                .addComponent(LEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(Panel_PLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLegislatura, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEnvioAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_PLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEnvio_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CLegislatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Validar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(Liberar)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_PLE_LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_PLE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_PLE_LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_PLE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void Btn_ValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ValidarActionPerformed
        // TODO add your handling code here:

        new Thread(() -> {

            ValPLE val = new ValPLE();
            try {
                if (!TEnvio.getSelectedItem().toString().trim().equals("")) {
                    Desabilita();
                    valores();
                    val.ValidacionPLE();
                    Habilita();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor de ingresar Legislatura", "Valida", JOptionPane.WARNING_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(ValidaPLE.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ValidaPLE.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "<html>Favor de revisar el archivo de observaciones. Si no se detectan observaciones, <b>recuerde realizar la liberación de la información tanto en Base de datos como en archivo de seguimiento</b>.</html>", "Recordatorio", JOptionPane.WARNING_MESSAGE);
        }).start();
    }//GEN-LAST:event_Btn_ValidarActionPerformed

    private void CEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEntidadActionPerformed
        // TODO add your handling code here:
        QGEN dat = new QGEN();
        asinga_NEntidad();
        LlenaComboLeg();
        llenaCombo();
    }//GEN-LAST:event_CEntidadActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here
        QGEN dat = new QGEN();
        LlenaComboLeg();
        llenaCombo();
        asinga_NEntidad();
    }//GEN-LAST:event_formWindowOpened

    public void LlenaComboLeg() {
        QGEN dat = new QGEN();
    CLegislatura.removeAllItems();

    ArrayEnvio = dat.Legislatura(CEntidad.getSelectedItem().toString().trim());

    float mayor = Float.MIN_VALUE;
    String valorMayor = "";

    for (String[] item : ArrayEnvio) {

        String valor = Arrays.toString(item).replace("[", "").replace("]", "");
        CLegislatura.addItem(valor);

        float numero = Float.parseFloat(valor); // convertir a número

        if (numero > mayor) {
            mayor = numero;
            valorMayor = valor;
        }
    }

    // seleccionar automáticamente el mayor
    CLegislatura.setSelectedItem(valorMayor);
    }

  public void llenaCombo() {
 QGEN dat = new QGEN();
    TEnvio.removeAllItems();
    TEnvio_anterior.removeAllItems();

    ArrayEnvio = dat.Envios(
            CEntidad.getSelectedItem().toString().trim(),
            CLegislatura.getSelectedItem().toString()
    );

    float maximo = Float.MIN_VALUE;

    for (String[] item : ArrayEnvio) {

        String valorStr = Arrays.toString(item).replace("[", "").replace("]", "").trim();

        TEnvio.addItem(valorStr);
        TEnvio_anterior.addItem(valorStr);

        float valor = Float.parseFloat(valorStr);

        if (valor > maximo) {
            maximo = valor;
        }
    }

    if (maximo != Float.MIN_VALUE) {
        float anterior = maximo - 1;

        TEnvio.setSelectedItem(String.valueOf((int) maximo));
        TEnvio_anterior.setSelectedItem(String.valueOf((int) anterior));
    }
}

    private void TEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEnvioActionPerformed
     
    }//GEN-LAST:event_TEnvioActionPerformed

    private void TEnvio_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEnvio_anteriorActionPerformed
     
    }//GEN-LAST:event_TEnvio_anteriorActionPerformed

    private void CLegislaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLegislaturaActionPerformed
        // TODO add your handling code here:
        if (CLegislatura.getSelectedIndex() > -1) {
            LlenaComboLeg();
        }

    }//GEN-LAST:event_CLegislaturaActionPerformed

    private void LiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiberarActionPerformed
        Querys Q=new Querys();
        Q.Cambio_Estatus(CEntidad.getSelectedItem().toString(), CLegislatura.getSelectedItem().toString(), TEnvio.getSelectedItem().toString(), "Liberado");
        JOptionPane.showMessageDialog(null, "<html>Se ha <b>liberado</b> la información para la <br>Entidad "+CEntidad.getSelectedItem().toString()+" </html>");
    }//GEN-LAST:event_LiberarActionPerformed

    public void Desabilita() {
        CEntidad.setEnabled(false);
        CLegislatura.setEnabled(false);
        TEnvio.setEnabled(false);
        TEnvio_anterior.setEnabled(false);
        Btn_Validar.setEnabled(false);
    }

    public void Habilita() {
        CEntidad.setEnabled(true);
        CLegislatura.setEnabled(true);
        TEnvio.setEnabled(true);
        TEnvio_anterior.setEnabled(true);
        Btn_Validar.setEnabled(true);

    }

    public void asinga_NEntidad() {
        if (CEntidad.getItemCount() > 0) {
            switch (CEntidad.getSelectedItem().toString()) {
                case "1":
                    LEntidad.setText("Aguascalientes");
                    break;
                case "2":
                    LEntidad.setText("Baja California");
                    break;
                case "3":
                    LEntidad.setText("Baja California Sur");
                    break;
                case "4":
                    LEntidad.setText("Campeche");
                    break;
                case "5":
                    LEntidad.setText("Coahuila de Zaragoza");
                    break;
                case "6":
                    LEntidad.setText("Colima");
                    break;
                case "7":
                    LEntidad.setText("Chiapas");
                    break;
                case "8":
                    LEntidad.setText("Chihuahua");
                    break;
                case "9":
                    LEntidad.setText("Ciudad de México");
                    break;
                case "10":
                    LEntidad.setText("Durango");
                    break;
                case "11":
                    LEntidad.setText("Guanajuato");
                    break;
                case "12":
                    LEntidad.setText("Guerrero");
                    break;
                case "13":
                    LEntidad.setText("Hidalgo");
                    break;
                case "14":
                    LEntidad.setText("Jalisco");
                    break;
                case "15":
                    LEntidad.setText("México");
                    break;
                case "16":
                    LEntidad.setText("Michoacán de Ocampo");
                    break;
                case "17":
                    LEntidad.setText("Morelos");
                    break;
                case "18":
                    LEntidad.setText("Nayarit");
                    break;
                case "19":
                    LEntidad.setText("Nuevo León");
                    break;
                case "20":
                    LEntidad.setText("Oaxaca");
                    break;
                case "21":
                    LEntidad.setText("Puebla");
                    break;
                case "22":
                    LEntidad.setText("Querétaro");
                    break;
                case "23":
                    LEntidad.setText("Quintana Roo");
                    break;
                case "24":
                    LEntidad.setText("San Luis Potosí");
                    break;
                case "25":
                    LEntidad.setText("Sinaloa");
                    break;
                case "26":
                    LEntidad.setText("Sonora");
                    break;
                case "27":
                    LEntidad.setText("Tabasco");
                    break;
                case "28":
                    LEntidad.setText("Tamaulipas");
                    break;
                case "29":
                    LEntidad.setText("Tlaxcala");
                    break;
                case "30":
                    LEntidad.setText("Veracruz de Ignacio de la Llave");
                    break;
                case "31":
                    LEntidad.setText("Yucatán");
                    break;
                case "32":
                    LEntidad.setText("Zacatecas");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "No se Encontro Entidad", "Valida", JOptionPane.WARNING_MESSAGE);
                    JOptionPane.showMessageDialog(null, "Favor de contactar al Administrador", "Valida", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidaPLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidaPLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidaPLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidaPLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidaPLE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner_verde;
    private javax.swing.JToggleButton Btn_Validar;
    private javax.swing.JComboBox CEntidad;
    private javax.swing.JComboBox CLegislatura;
    private javax.swing.JLabel LEntidad;
    private javax.swing.JLabel LabelEntidad;
    private javax.swing.JLabel LabelEnvio;
    private javax.swing.JLabel LabelEnvioAnterior;
    private javax.swing.JLabel LabelLegislatura;
    private javax.swing.JLabel Label_Titulo;
    private javax.swing.JLabel Label_logo;
    private javax.swing.JButton Liberar;
    private javax.swing.JPanel Panel_PLE;
    private javax.swing.JPanel Panel_PLE_LOGO;
    private javax.swing.JComboBox TEnvio;
    private javax.swing.JComboBox TEnvio_anterior;
    // End of variables declaration//GEN-END:variables
}
