/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_PLE;

import ValidacionesPle.QuerysValPLE.QGEN;
import ValidacionesPle.ValPLE;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ANTONIO.CORIA
 */
public class ValidaPLE extends javax.swing.JFrame {

    /**
     * 
     * Creates new form ValidaPLE
     */
    public static String entidad="",legislatura="",envio="",Nomentidad="",envio_anterior="";
     ArrayList<String[]> ArrayEnvio;
    
    
    public ValidaPLE() {
        initComponents();
        this.setLocationRelativeTo(null);
       // this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO
        
    }
    
    
    public void valores()
    {
        entidad=CEntidad.getSelectedItem().toString().trim();
        Nomentidad=LEntidad.getText().trim();
        legislatura=CLegislatura.getSelectedItem().toString();
        envio=TEnvio.getSelectedItem().toString().trim();
        envio_anterior=TEnvio_anterior.getSelectedItem().toString().trim();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CEntidad = new javax.swing.JComboBox();
        ENVIO1 = new javax.swing.JLabel();
        ENVIO = new javax.swing.JLabel();
        TEnvio = new javax.swing.JComboBox();
        jToggleButton1 = new javax.swing.JToggleButton();
        LEntidad = new javax.swing.JLabel();
        TEnvio_anterior = new javax.swing.JComboBox();
        ENVIO2 = new javax.swing.JLabel();
        CLegislatura = new javax.swing.JComboBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo CNG.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setText("Poderes Legislativos Estatales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Entidad:");

        CEntidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));
        CEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEntidadActionPerformed(evt);
            }
        });

        ENVIO1.setText("Legislatura:");

        ENVIO.setText("Envio:");

        TEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEnvioActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Validar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        LEntidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        TEnvio_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEnvio_anteriorActionPerformed(evt);
            }
        });

        ENVIO2.setText("Envio anterior:");

        CLegislatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLegislaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(LEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 240, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ENVIO1)
                    .addComponent(CLegislatura, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ENVIO)
                        .addGap(18, 18, 18)
                        .addComponent(ENVIO2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TEnvio_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(303, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ENVIO1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ENVIO, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ENVIO2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEnvio_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CLegislatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Menu men=new Menu();
        men.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Menu men=new Menu();
        men.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        
        new Thread(() -> {

            ValPLE val = new ValPLE();
            try {
                    if (!TEnvio.getSelectedItem().toString().trim().equals("")) {

                        Desabilita();
                        valores();
                        val.ValidacionPLE();
                        Habilita();
                    } else {
                        JOptionPane.showMessageDialog(null, "Favor de ingresar Legislatura", "Valida", JOptionPane.WARNING_MESSAGE);
                    }
            } catch (IOException ex) {
                Logger.getLogger(ValidaPLE.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ValidaPLE.class.getName()).log(Level.SEVERE, null, ex);
            }

        }).start();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void CEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEntidadActionPerformed
        // TODO add your handling code here:
        QGEN dat=new QGEN();
        asinga_NEntidad();
        LlenaComboLeg();
       llenaCombo();
    }//GEN-LAST:event_CEntidadActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here
        QGEN dat=new QGEN();
       LlenaComboLeg();
        llenaCombo();
        asinga_NEntidad();
    }//GEN-LAST:event_formWindowOpened

    
    public void LlenaComboLeg(){
         QGEN dat=new QGEN();
          CLegislatura.removeAllItems();
         ArrayEnvio = dat.Legislatura(CEntidad.getSelectedItem().toString().trim());
          for (String[] item : ArrayEnvio) {
            CLegislatura.addItem(Arrays.toString(item).replace("[", "").replace("]", ""));
           
        }
    }
    
    public void llenaCombo(){
         QGEN dat=new QGEN();
          TEnvio.removeAllItems();
          TEnvio_anterior.removeAllItems();
         ArrayEnvio = dat.Envios(CEntidad.getSelectedItem().toString().trim(), CLegislatura.getSelectedItem().toString());
          for (String[] item : ArrayEnvio) {
            TEnvio.addItem(Arrays.toString(item).replace("[", "").replace("]", ""));
            TEnvio_anterior.addItem(Arrays.toString(item).replace("[", "").replace("]", ""));
        }
    }
    
    private void TEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEnvioActionPerformed

    private void TEnvio_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEnvio_anteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEnvio_anteriorActionPerformed

    private void CLegislaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLegislaturaActionPerformed
        // TODO add your handling code here:
      if( CLegislatura.getSelectedIndex() > -1)
       {
           llenaCombo();  
       }
        
    }//GEN-LAST:event_CLegislaturaActionPerformed

    
    public void Desabilita(){
      CEntidad.setEnabled(false);
      CLegislatura.setEnabled(false);
      TEnvio.setEnabled(false);
      TEnvio_anterior.setEnabled(false);
      jToggleButton1.setEnabled(false);
    }
    
     public void Habilita(){
          CEntidad.setEnabled(true);
      CLegislatura.setEnabled(true);
      TEnvio.setEnabled(true);
      TEnvio_anterior.setEnabled(true);
      jToggleButton1.setEnabled(true);
        
    }
    
    public void asinga_NEntidad(){
         if (CEntidad.getItemCount()>0)
    {
        switch(CEntidad.getSelectedItem().toString()){
            case "1":
             LEntidad.setText("Aguascalientes");
                break;
            case "2":
             LEntidad.setText("Baja California");
                break;
            case "3":
                LEntidad.setText("Baja California Sur");
                break;
            case "4":
                LEntidad.setText("Campeche");
                break;
            case "5":
                LEntidad.setText("Coahuila de Zaragoza");
                break;
            case "6":
                LEntidad.setText("Colima");
                break;
            case "7":
                LEntidad.setText("Chiapas");
                break;
            case "8":
                LEntidad.setText("Chihuahua");
                break;
            case "9":
                LEntidad.setText("Ciudad de México");
                break;
            case "10":
                LEntidad.setText("Durango");
                break;
            case "11":
                LEntidad.setText("Guanajuato");
                break;
            case "12":
                LEntidad.setText("Guerrero");
                break;
            case "13":
                LEntidad.setText("Hidalgo");
                break;
            case "14":
                LEntidad.setText("Jalisco");
                break;
            case "15":
                LEntidad.setText("México");
                break;
            case "16":
                LEntidad.setText("Michoacán de Ocampo");
                break;
            case "17":
                LEntidad.setText("Morelos");
                break;
            case "18":
                LEntidad.setText("Nayarit");
                break;
            case "19":
                LEntidad.setText("Nuevo León");
                break;
            case "20":
                LEntidad.setText("Oaxaca");
                break;
            case "21":
                LEntidad.setText("Puebla");
                break;
            case "22":
                LEntidad.setText("Querétaro");
                break;
            case "23":
                LEntidad.setText("Quintana Roo");
                break;
            case "24":
                LEntidad.setText("San Luis Potosí");
                break;
            case "25":
                LEntidad.setText("Sinaloa");
                break;
            case "26":
                LEntidad.setText("Sonora");
                break;
            case "27":
                LEntidad.setText("Tabasco");
                break;
            case "28":
                LEntidad.setText("Tamaulipas");
                break;
            case "29":
                LEntidad.setText("Tlaxcala");
                break;
            case "30":
                LEntidad.setText("Veracruz de Ignacio de la Llave");
                break;
            case "31":
                LEntidad.setText("Yucatán");
                break;
            case "32":
                LEntidad.setText("Zacatecas");
                break;
            default:
                JOptionPane.showMessageDialog(null, "No se Encontro Entidad", "Valida", JOptionPane.WARNING_MESSAGE);
                JOptionPane.showMessageDialog(null, "Favor de contactar al Administrador", "Valida", JOptionPane.WARNING_MESSAGE);
        }
    }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidaPLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidaPLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidaPLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidaPLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidaPLE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CEntidad;
    private javax.swing.JComboBox CLegislatura;
    private javax.swing.JLabel ENVIO;
    private javax.swing.JLabel ENVIO1;
    private javax.swing.JLabel ENVIO2;
    private javax.swing.JLabel LEntidad;
    private javax.swing.JComboBox TEnvio;
    private javax.swing.JComboBox TEnvio_anterior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
