/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas_JA;

import Pantallas_JA.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Year;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.org.inegi.Procedure.JA.*;
import mx.org.inegi.conexion.JA.*;

/**
 *
 * @author LAURA.MEDINAJ
 */
public class CreaEBD_JA extends javax.swing.JFrame {

    public static String JAYear = "";
    DaoConexionJA conn = new DaoConexionJA();
    ResultSet resul;
    String sql = "";

    public CreaEBD_JA() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        Field_JAYear.setEnabled(false);
        Field_JAYear.setText(String.valueOf(Year.now().getValue()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelColor_RosaSalmon = new javax.swing.JPanel();
        Label_iconJA = new javax.swing.JLabel();
        LabelPeocuraduria_Agraria = new javax.swing.JLabel();
        Button_CrearEBD = new javax.swing.JButton();
        Field_JAYear = new javax.swing.JTextField();
        Button_otheryear = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        PanelColor_RosaSalmon.setBackground(new java.awt.Color(250, 128, 114));

        javax.swing.GroupLayout PanelColor_RosaSalmonLayout = new javax.swing.GroupLayout(PanelColor_RosaSalmon);
        PanelColor_RosaSalmon.setLayout(PanelColor_RosaSalmonLayout);
        PanelColor_RosaSalmonLayout.setHorizontalGroup(
            PanelColor_RosaSalmonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelColor_RosaSalmonLayout.setVerticalGroup(
            PanelColor_RosaSalmonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        Label_iconJA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo CNG.png"))); // NOI18N

        LabelPeocuraduria_Agraria.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        LabelPeocuraduria_Agraria.setText("Procuraduría Agraria");

        Button_CrearEBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CreaEBD_JA.jpg"))); // NOI18N
        Button_CrearEBD.setText("Crear EBD");
        Button_CrearEBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CrearEBDActionPerformed(evt);
            }
        });

        Field_JAYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_JAYearActionPerformed(evt);
            }
        });

        Button_otheryear.setText("Otro año");
        Button_otheryear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_otheryearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelColor_RosaSalmon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 85, Short.MAX_VALUE)
                        .addComponent(LabelPeocuraduria_Agraria)
                        .addGap(70, 70, 70)
                        .addComponent(Label_iconJA, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_CrearEBD)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Field_JAYear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_otheryear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Label_iconJA))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(LabelPeocuraduria_Agraria)))
                .addGap(18, 18, 18)
                .addComponent(PanelColor_RosaSalmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Field_JAYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_otheryear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(Button_CrearEBD)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Menu_JA Menu = new Menu_JA();
        Menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void Field_JAYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_JAYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_JAYearActionPerformed

    private void Button_otheryearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_otheryearActionPerformed
        Field_JAYear.setText("");
        Field_JAYear.setEnabled(true);
    }//GEN-LAST:event_Button_otheryearActionPerformed

    private void Button_CrearEBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CrearEBDActionPerformed
        JAYear = Field_JAYear.getText();
        int existetabla = 0;
         CreaTRDinamica_JA crea_TRDinamicaJA = new CreaTRDinamica_JA();
        int crear = JOptionPane.showConfirmDialog( // Preguntar si queremos crear tablas dinámicas
                CreaEBD_JA.this, "¿Está seguro de crear tablas dinámicas JA " + JAYear + "?",
                "Confirmar creación de estructura", JOptionPane.YES_NO_OPTION);
        Button_CrearEBD.setEnabled(false);

        if (crear == JOptionPane.YES_OPTION) { //En caso de responder "Sí"
            try {
                existetabla = crea_TRDinamicaJA.ValExistenTablas(); //verificar si existen tablas dinámicas JA
            } catch (SQLException ex) {
                Logger.getLogger(CreaEBD_JA.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (existetabla > 0) { //En caso de existir tablas
                JOptionPane.showMessageDialog(null, "Ya existen tablas dinámicas JA para el año " + JAYear);
                Button_CrearEBD.setEnabled(true);
            } else { //Si no existen tablas dinámicas se crearán
               
                try {
                    System.out.println("Llamando procedimiento para crear tablas dinámicas en BD");       
                    if(crea_TRDinamicaJA.CreaTablas()){
                    JOptionPane.showMessageDialog(CreaEBD_JA.this, "Las tablas dinámicas han sido creadas");
                    }else{
                    JOptionPane.showMessageDialog(CreaEBD_JA.this, "Error al crear las tablas dinámicas, favor de revisar con el administrador");
                    
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(CreaEBD_JA.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
        else { //En caso de responder "No"
            JOptionPane.showMessageDialog(CreaEBD_JA.this, "Acción cancelada.");
        }
    }//GEN-LAST:event_Button_CrearEBDActionPerformed

    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreaEBD_JA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreaEBD_JA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreaEBD_JA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreaEBD_JA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreaEBD_JA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_CrearEBD;
    private javax.swing.JButton Button_otheryear;
    private static javax.swing.JTextField Field_JAYear;
    private javax.swing.JLabel LabelPeocuraduria_Agraria;
    private javax.swing.JLabel Label_iconJA;
    private javax.swing.JPanel PanelColor_RosaSalmon;
    // End of variables declaration//GEN-END:variables
}
