/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas_JA;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.org.inegi.ExportaXlsm.JA.Exporta_errores_insert_TRJA;
import mx.org.inegi.QuerysGeneral.JA.Querys_JA;
import mx.org.inegi.insert_TR.JA.TR_JA_ACTOS_PROCESALES;
import mx.org.inegi.insert_TR.JA.TR_JA_ASUNTOS_HIDROCARBUROS;
import mx.org.inegi.insert_TR.JA.TR_JA_CONCLUSIONES;
import mx.org.inegi.insert_TR.JA.TR_JA_CONTROL;
import mx.org.inegi.insert_TR.JA.TR_JA_CUMPLIM_EJECUTORIAS;
import mx.org.inegi.insert_TR.JA.TR_JA_EXHORTOS_DESPACHOS;
import mx.org.inegi.insert_TR.JA.TR_JA_INGRESOS;
import mx.org.inegi.insert_TR.JA.TR_JA_TRAMITE;

/**
 *
 * @author ANDREA.HERNANDEZL
 */
public class ErroresInsertTR_JA extends javax.swing.JFrame {

    /**
     * Creates new form ErroresInsertTR_JA
     */
    public ErroresInsertTR_JA() {
        initComponents();
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        jProgressBar1.setVisible(false);
        BExportaxlms.setVisible(true);
        jTextArea1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        BExportaxlms = new javax.swing.JButton();
        BActualiza = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TABLA", "REG_ID", "EXCEPTION"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        BExportaxlms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ExportaExcel.png.jpg"))); // NOI18N
        BExportaxlms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExportaxlmsActionPerformed(evt);
            }
        });

        BActualiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualiza.svg.jpg"))); // NOI18N
        BActualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActualizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BExportaxlms)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(BActualiza, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BExportaxlms)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BActualiza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BActualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizaActionPerformed
        // TODO add your handling code here:
        new Thread(() -> {
            limpiarTabla();
            MuestraError();
        }).start();
    }

    public void limpiarTabla() {
        DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
        while (TablaError.getRowCount() > 0) {
            TablaError.removeRow(0);
        }
    }

    public void MuestraError() {
        try {
            IntegraJA_TR IntTR = new IntegraJA_TR();
            String Texto = "";
            String regTMPSQL = "", regTRSQL = "", regTRSQLNI = "", RegValidacion = "";
            int regTCSV = 0;
            ArrayList<String[]> ArrayErroresIns;

            TR_JA_ACTOS_PROCESALES AP = new TR_JA_ACTOS_PROCESALES();
            TR_JA_ASUNTOS_HIDROCARBUROS AH = new TR_JA_ASUNTOS_HIDROCARBUROS();
            TR_JA_CONCLUSIONES CONC = new TR_JA_CONCLUSIONES();
            TR_JA_CONTROL CONT = new TR_JA_CONTROL();
            TR_JA_CUMPLIM_EJECUTORIAS CE = new TR_JA_CUMPLIM_EJECUTORIAS();
            TR_JA_EXHORTOS_DESPACHOS ED = new TR_JA_EXHORTOS_DESPACHOS();
            TR_JA_INGRESOS ING = new TR_JA_INGRESOS();
            TR_JA_TRAMITE TRA = new TR_JA_TRAMITE();
            Querys_JA Q = new Querys_JA();
            
            int[] ArryTotalCSV = new int[8];
            ArryTotalCSV[0] = AP.CFilas2;
            ArryTotalCSV[1] = AH.CFilas2;
            ArryTotalCSV[2] = CONC.CFilas2;
            ArryTotalCSV[3] = CONT.CFilas2;
            ArryTotalCSV[4] = CE.CFilas2;
            ArryTotalCSV[5] = ED.CFilas2;
            ArryTotalCSV[6] = ING.CFilas2;
            ArryTotalCSV[7] = TRA.CFilas2;
            
            String[] ArrayTablasTR = new String[26];
            ArrayTablasTR[0] = "TR_JA_ACTOS_PROCESALES_GEN";
            ArrayTablasTR[1] = "TR_JA_ASUNTOS_HIDROCARBUROS_GEN";
            ArrayTablasTR[2] = "TR_JA_CONCLUSIONES_GEN";
            ArrayTablasTR[3] = "TR_JA_CONTROL_GEN";
            ArrayTablasTR[4] = "TR_JA_CUMPLIM_EJECUTORIAS_GEN";
            ArrayTablasTR[5] = "TR_JA_EXHORTOS_DESPACHOS_GEN";
            ArrayTablasTR[6] = "TR_JA_INGRESOS_GEN";
            ArrayTablasTR[7] = "TR_JA_TRAMITE_GEN";
            
            ArrayErroresIns = Q.TotalErrores_insert_TR();
            
            int Contador = 30;
            for (int i = 0; i < 8; i++) {
                regTCSV = ArryTotalCSV[i];
                regTRSQL = Q.Total_Reg_TR(ArrayTablasTR[i]);
                regTRSQLNI = Q.Total_Reg_NITR(ArrayTablasTR[i]);
                Texto = Texto + "" + ArrayTablasTR[i] + ": \n"
                        + "Reg_CFilas:" + ArryTotalCSV[i] + "  Reg_TR:" + regTRSQL + "  Reg_TRNI:" + regTRSQLNI + "\n \n";

                jProgressBar1.setValue(Contador);
                    Contador = Contador + 35;
            }
            jTextArea1.setText(Texto);
            jTextArea1.setVisible(true);
            
            if (ArrayErroresIns.size() > 0) {
                String[] errorarray;
                String part0 = "", part1 = "", part2 = "";
                DefaultTableModel TablaError = (DefaultTableModel) jTable1.getModel();
                Object[] fila = new Object[3];
                for (int j = 0; j < ArrayErroresIns.size(); j++) {
                    String Datos = Arrays.toString(ArrayErroresIns.get(j)).replace("[", "").replace("]", "");
                    errorarray = Datos.split(",");
                    part0 = errorarray[0].trim();
                    part1 = errorarray[1].trim();
                    part2 = errorarray[2].trim();
                    fila[0] = part0;
                    fila[1] = part1;
                    fila[2] = part2;
                    TablaError.addRow(fila);
                    Class<?> col_class = jTable1.getColumnClass(0);
                    jTable1.setDefaultEditor(col_class, null);
                }
                BExportaxlms.setVisible(true);
            } else {

                JOptionPane.showMessageDialog(null, "No se encontraron registros con Error de insert", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ErroresInsertTR_JA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BActualizaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        IntegraJA_TR.ventanaAbierta = false;
    }//GEN-LAST:event_formWindowClosing

    private void BExportaxlmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExportaxlmsActionPerformed
        // TODO add your handling code here:
        IntegraJA_TR PIntegra = new IntegraJA_TR();
        Exporta_errores_insert_TRJA ErroresInsert = new Exporta_errores_insert_TRJA();
        try {
            ErroresInsert.exportarExcel(jTable1, PIntegra.Año);

        } catch (IOException ex) {
            Logger.getLogger(ErroresInsertTR_JA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BExportaxlmsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ErroresInsertTR_JA.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ErroresInsertTR_JA.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ErroresInsertTR_JA.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ErroresInsertTR_JA.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ErroresInsertTR_JA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualiza;
    private javax.swing.JButton BExportaxlms;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
