/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas_JA;

import Convertir_CSV.Convertir_CSV;
import java.awt.Color;
import java.awt.FileDialog;
import java.io.File;
import javax.swing.JOptionPane;
import mx.org.inegi.Procedure.JA.EliminaBDJATRGEN;
import mx.org.inegi.insert_TR.JA.TR_JA_ACTOS_PROCESALES;
import mx.org.inegi.insert_TR.JA.TR_JA_ASUNTOS_HIDROCARBUROS;
import mx.org.inegi.insert_TR.JA.TR_JA_CONCLUSIONES;
import mx.org.inegi.insert_TR.JA.TR_JA_CONTROL;
import mx.org.inegi.insert_TR.JA.TR_JA_CUMPLIM_EJECUTORIAS;
import mx.org.inegi.insert_TR.JA.TR_JA_EXHORTOS_DESPACHOS;
import mx.org.inegi.insert_TR.JA.TR_JA_INGRESOS;
import mx.org.inegi.insert_TR.JA.TR_JA_TRAMITE;

/**
 *
 * @author ANDREA.HERNANDEZL
 */
public class IntegraJA_TR extends javax.swing.JFrame {

    /**
     * Creates new form Inserta_TR
     */
    public static String RutaAr = "", Año = "";
    public static boolean ventanaAbierta = false;
    public static String directorio = "";
    String nombreArchivo = "";

    public IntegraJA_TR() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        Progressbar_Cargando.setVisible(false);
        ErroresInsert.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_icon_JA = new javax.swing.JLabel();
        Label_Titulo_JA = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Label_RutaArchivo = new javax.swing.JLabel();
        RutaArchivo = new javax.swing.JTextField();
        Button_Ruta = new javax.swing.JButton();
        Button_Integrar = new javax.swing.JButton();
        Button_Nota = new javax.swing.JButton();
        Progressbar_Cargando = new javax.swing.JProgressBar();
        Label_Progressbar = new javax.swing.JLabel();
        ErroresInsert = new javax.swing.JButton();

        setName("Frame_JA_IntegraTR"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Label_icon_JA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo CNG.png"))); // NOI18N

        Label_Titulo_JA.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Label_Titulo_JA.setText("Procuraduría Agraria");

        jPanel1.setBackground(new java.awt.Color(250, 128, 114));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        Label_RutaArchivo.setText("Ruta Archivo:");

        RutaArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutaArchivoActionPerformed(evt);
            }
        });

        Button_Ruta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Button_Ruta.setText(". . .");
        Button_Ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RutaActionPerformed(evt);
            }
        });

        Button_Integrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InsertaTR_JA.jpg"))); // NOI18N
        Button_Integrar.setText("Integrar TR");
        Button_Integrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_IntegrarActionPerformed(evt);
            }
        });

        Button_Nota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nota.png"))); // NOI18N
        Button_Nota.setText("Nota");
        Button_Nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_NotaActionPerformed(evt);
            }
        });

        Label_Progressbar.setText(" ");

        ErroresInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ErroresInsert.jpg"))); // NOI18N
        ErroresInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErroresInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 99, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Label_Titulo_JA)
                                .addGap(91, 91, 91)
                                .addComponent(Label_icon_JA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Button_Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Button_Nota)
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Label_RutaArchivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RutaArchivo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Progressbar_Cargando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Label_Progressbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Integrar)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ErroresInsert)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_icon_JA)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Label_Titulo_JA)))
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_Nota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ErroresInsert)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_RutaArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Ruta)
                        .addGap(64, 64, 64)
                        .addComponent(Button_Integrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Progressbar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Progressbar_Cargando, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Menu_JA Menu = new Menu_JA();
        Menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void RutaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutaArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RutaArchivoActionPerformed

    private void Button_IntegrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_IntegrarActionPerformed
        // TODO add your handling code here:
        TR_JA_ACTOS_PROCESALES AP = new TR_JA_ACTOS_PROCESALES();
        TR_JA_ASUNTOS_HIDROCARBUROS AH = new TR_JA_ASUNTOS_HIDROCARBUROS();
        TR_JA_CONCLUSIONES CONC = new TR_JA_CONCLUSIONES();
        TR_JA_CONTROL CONT = new TR_JA_CONTROL();
        TR_JA_CUMPLIM_EJECUTORIAS CE = new TR_JA_CUMPLIM_EJECUTORIAS();
        TR_JA_EXHORTOS_DESPACHOS ED = new TR_JA_EXHORTOS_DESPACHOS();
        TR_JA_INGRESOS ING = new TR_JA_INGRESOS();
        TR_JA_TRAMITE TRA = new TR_JA_TRAMITE();

        EliminaBDJATRGEN elimina = new EliminaBDJATRGEN();
        Convertir_CSV convert = new Convertir_CSV();       
        new Thread(() -> {
            try {
                int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de insertar a TR?", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (respuesta == JOptionPane.YES_OPTION) {
                    if (!RutaArchivo.getText().equals("")) {
                        muestra();
                        //elimina.EliminaBD();
                        Button_Integrar.setEnabled(false);
                        convert.Convierte(RutaAr); //convierte archivo XLS a CSV
                        Progressbar_Cargando.setValue(5);
                        Label_Progressbar.setText("Insertando... TR_JA_ACTOS_PROCESALES_GEN");
                        Progressbar_Cargando.setValue(18);
                        AP.TR_JA_ACTOS_PROCESALES();
                        Label_Progressbar.setText("Insertando... TR_JA_ASUNTOS_HIDROCARBUROS_GEN");
                        Progressbar_Cargando.setValue(31);
                        AH.TR_JA_ASUNTOS_HIDROCARBUROS();
                        Label_Progressbar.setText("Insertando... TR_JA_CONCLUSIONES_GEN");
                        Progressbar_Cargando.setValue(44);
                        CONC.TR_JA_CONCLUSIONES();
                        Label_Progressbar.setText("Insertando... TR_JA_CONTROL_GEN");
                        Progressbar_Cargando.setValue(57);
                        CONT.TR_JA_CONTROL();
                        Label_Progressbar.setText("Insertando... TR_JA_CUMPLIM_EJECUTORIAS_GEN");
                        Progressbar_Cargando.setValue(70);
                        CE.TR_JA_CUMPLIM_EJECUTORIAS();
                        Label_Progressbar.setText("Insertando... TR_JA_EXHORTOS_DESPACHOS_GEN");
                        Progressbar_Cargando.setValue(83);
                        ED.TR_JA_EXHORTOS_DESPACHOS();
                        Label_Progressbar.setText("Insertando... TR_JA_INGRESOS_GEN");
                        Progressbar_Cargando.setValue(96);
                        ING.TR_JA_INGRESOS();
                        Label_Progressbar.setText("Insertando... TR_JA_TRAMITE_GEN");
                        TRA.TR_JA_TRAMITE();
                        Progressbar_Cargando.setValue(100);

                        oculta();

                        JOptionPane.showMessageDialog(null, "La información se ha insertado favor de revisar Ventana Errores de insert");
                        ErroresInsert.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Favor de seleccionar archivo");
                    }
                }
            } catch (Exception ex) {
            }
        }).start();
    }//GEN-LAST:event_Button_IntegrarActionPerformed

    public void muestra() {
        Button_Integrar.setEnabled(false);
        Label_Progressbar.setEnabled(false);
        Progressbar_Cargando.setVisible(true);
    }

    public void oculta() {
        Button_Integrar.setEnabled(true);
        Label_Progressbar.setVisible(false);
        Progressbar_Cargando.setVisible(false);
    }
    private void Button_NotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_NotaActionPerformed
        // TODO add your handling code here:
        Nota_JA Nota = new Nota_JA();
        Nota.setVisible(true);
    }//GEN-LAST:event_Button_NotaActionPerformed

    private void Button_RutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RutaActionPerformed
        // TODO add your handling code here:
        RutaArchivo.setText("");
        FileDialog dialogoArchivo;
        dialogoArchivo = new FileDialog(this, "ARCHIVOS JA", FileDialog.LOAD);
        dialogoArchivo.setVisible(true);
        if (dialogoArchivo.getFile() != null) {
            directorio = dialogoArchivo.getDirectory();
            System.out.println("directorio: "+directorio);
            nombreArchivo = dialogoArchivo.getFile();
            RutaArchivo.setText(directorio + nombreArchivo);
            RutaAr = directorio + nombreArchivo;
        }
    }//GEN-LAST:event_Button_RutaActionPerformed

    private void ErroresInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErroresInsertActionPerformed
        // TODO add your handling code here:
        if (!ventanaAbierta) {
            ventanaAbierta = true;
            ErroresInsertTR_JA Errores = new ErroresInsertTR_JA();
            Errores.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Ventana Errores de insert abierta");
        }
    }//GEN-LAST:event_ErroresInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntegraJA_TR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntegraJA_TR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntegraJA_TR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntegraJA_TR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntegraJA_TR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Integrar;
    private javax.swing.JButton Button_Nota;
    private javax.swing.JButton Button_Ruta;
    private javax.swing.JButton ErroresInsert;
    private javax.swing.JLabel Label_Progressbar;
    private javax.swing.JLabel Label_RutaArchivo;
    private javax.swing.JLabel Label_Titulo_JA;
    private javax.swing.JLabel Label_icon_JA;
    private javax.swing.JProgressBar Progressbar_Cargando;
    private javax.swing.JTextField RutaArchivo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
